// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "Loop_2_proc.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic Loop_2_proc::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic Loop_2_proc::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<11> Loop_2_proc::ap_ST_fsm_state1 = "1";
const sc_lv<11> Loop_2_proc::ap_ST_fsm_state2 = "10";
const sc_lv<11> Loop_2_proc::ap_ST_fsm_state3 = "100";
const sc_lv<11> Loop_2_proc::ap_ST_fsm_state4 = "1000";
const sc_lv<11> Loop_2_proc::ap_ST_fsm_state5 = "10000";
const sc_lv<11> Loop_2_proc::ap_ST_fsm_state6 = "100000";
const sc_lv<11> Loop_2_proc::ap_ST_fsm_state7 = "1000000";
const sc_lv<11> Loop_2_proc::ap_ST_fsm_state8 = "10000000";
const sc_lv<11> Loop_2_proc::ap_ST_fsm_state9 = "100000000";
const sc_lv<11> Loop_2_proc::ap_ST_fsm_state10 = "1000000000";
const sc_lv<11> Loop_2_proc::ap_ST_fsm_state11 = "10000000000";
const sc_lv<32> Loop_2_proc::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> Loop_2_proc::ap_const_lv32_9 = "1001";
const sc_lv<32> Loop_2_proc::ap_const_lv32_A = "1010";
const sc_lv<32> Loop_2_proc::ap_const_lv32_1 = "1";
const sc_lv<1> Loop_2_proc::ap_const_lv1_0 = "0";
const sc_lv<32> Loop_2_proc::ap_const_lv32_2 = "10";
const sc_lv<32> Loop_2_proc::ap_const_lv32_3 = "11";
const sc_lv<32> Loop_2_proc::ap_const_lv32_4 = "100";
const sc_lv<32> Loop_2_proc::ap_const_lv32_5 = "101";
const sc_lv<32> Loop_2_proc::ap_const_lv32_6 = "110";
const sc_lv<32> Loop_2_proc::ap_const_lv32_7 = "111";
const sc_lv<32> Loop_2_proc::ap_const_lv32_8 = "1000";
const sc_lv<2> Loop_2_proc::ap_const_lv2_0 = "00";
const sc_lv<2> Loop_2_proc::ap_const_lv2_3 = "11";
const sc_lv<2> Loop_2_proc::ap_const_lv2_1 = "1";
const sc_lv<2> Loop_2_proc::ap_const_lv2_2 = "10";
const sc_lv<32> Loop_2_proc::ap_const_lv32_13 = "10011";
const sc_lv<20> Loop_2_proc::ap_const_lv20_0 = "00000000000000000000";
const sc_lv<12> Loop_2_proc::ap_const_lv12_FFF = "111111111111";
const sc_lv<1> Loop_2_proc::ap_const_lv1_1 = "1";
const sc_lv<32> Loop_2_proc::ap_const_lv32_14 = "10100";
const sc_lv<5> Loop_2_proc::ap_const_lv5_D = "1101";
const sc_lv<32> Loop_2_proc::ap_const_lv32_FFFFFFE8 = "11111111111111111111111111101000";
const sc_lv<32> Loop_2_proc::ap_const_lv32_1F = "11111";
const sc_lv<20> Loop_2_proc::ap_const_lv20_FFFFF = "11111111111111111111";
const sc_lv<32> Loop_2_proc::ap_const_lv32_FFFFFFE7 = "11111111111111111111111111100111";
const sc_lv<32> Loop_2_proc::ap_const_lv32_19 = "11001";
const sc_lv<31> Loop_2_proc::ap_const_lv31_0 = "0000000000000000000000000000000";
const sc_lv<20> Loop_2_proc::ap_const_lv20_FFFE8 = "11111111111111101000";
const sc_lv<32> Loop_2_proc::ap_const_lv32_3F = "111111";
const sc_lv<8> Loop_2_proc::ap_const_lv8_7F = "1111111";
const sc_lv<8> Loop_2_proc::ap_const_lv8_7E = "1111110";
const sc_lv<8> Loop_2_proc::ap_const_lv8_8 = "1000";
const sc_lv<32> Loop_2_proc::ap_const_lv32_17 = "10111";
const bool Loop_2_proc::ap_const_boolean_1 = true;

Loop_2_proc::Loop_2_proc(sc_module_name name) : sc_module(name), mVcdFile(0) {
    myproject_axi_mux_32_20_1_1_U585 = new myproject_axi_mux_32_20_1_1<1,1,20,20,20,2,20>("myproject_axi_mux_32_20_1_1_U585");
    myproject_axi_mux_32_20_1_1_U585->din0(tmp_data_V_0);
    myproject_axi_mux_32_20_1_1_U585->din1(tmp_data_V_1);
    myproject_axi_mux_32_20_1_1_U585->din2(tmp_data_V_2);
    myproject_axi_mux_32_20_1_1_U585->din3(j3_0_i_reg_140);
    myproject_axi_mux_32_20_1_1_U585->dout(tmp_V_3_fu_174_p5);
    myproject_axi_lshr_32ns_32ns_32_2_1_U586 = new myproject_axi_lshr_32ns_32ns_32_2_1<1,2,1,32,32,32>("myproject_axi_lshr_32ns_32ns_32_2_1_U586");
    myproject_axi_lshr_32ns_32ns_32_2_1_U586->clk(ap_clk);
    myproject_axi_lshr_32ns_32ns_32_2_1_U586->reset(ap_rst);
    myproject_axi_lshr_32ns_32ns_32_2_1_U586->din0(grp_fu_370_p0);
    myproject_axi_lshr_32ns_32ns_32_2_1_U586->din1(add_ln958_reg_566);
    myproject_axi_lshr_32ns_32ns_32_2_1_U586->ce(ap_var_for_const0);
    myproject_axi_lshr_32ns_32ns_32_2_1_U586->dout(grp_fu_370_p2);
    myproject_axi_shl_64ns_32ns_64_2_1_U587 = new myproject_axi_shl_64ns_32ns_64_2_1<1,2,0,64,32,64>("myproject_axi_shl_64ns_32ns_64_2_1_U587");
    myproject_axi_shl_64ns_32ns_64_2_1_U587->clk(ap_clk);
    myproject_axi_shl_64ns_32ns_64_2_1_U587->reset(ap_rst);
    myproject_axi_shl_64ns_32ns_64_2_1_U587->din0(grp_fu_378_p0);
    myproject_axi_shl_64ns_32ns_64_2_1_U587->din1(grp_fu_378_p1);
    myproject_axi_shl_64ns_32ns_64_2_1_U587->ce(ap_var_for_const0);
    myproject_axi_shl_64ns_32ns_64_2_1_U587->dout(grp_fu_378_p2);
    regslice_both_out_data_U = new regslice_both<32>("regslice_both_out_data_U");
    regslice_both_out_data_U->ap_clk(ap_clk);
    regslice_both_out_data_U->ap_rst(ap_rst);
    regslice_both_out_data_U->data_in(out_r_TDATA_int);
    regslice_both_out_data_U->vld_in(out_r_TVALID_int);
    regslice_both_out_data_U->ack_in(out_r_TREADY_int);
    regslice_both_out_data_U->data_out(out_r_TDATA);
    regslice_both_out_data_U->vld_out(regslice_both_out_data_U_vld_out);
    regslice_both_out_data_U->ack_out(out_r_TREADY);
    regslice_both_out_data_U->apdone_blk(regslice_both_out_data_U_apdone_blk);
    regslice_both_out_last_V_U = new regslice_both<1>("regslice_both_out_last_V_U");
    regslice_both_out_last_V_U->ap_clk(ap_clk);
    regslice_both_out_last_V_U->ap_rst(ap_rst);
    regslice_both_out_last_V_U->data_in(last_reg_488);
    regslice_both_out_last_V_U->vld_in(out_r_TVALID_int);
    regslice_both_out_last_V_U->ack_in(regslice_both_out_last_V_U_ack_in_dummy);
    regslice_both_out_last_V_U->data_out(out_r_TLAST);
    regslice_both_out_last_V_U->vld_out(regslice_both_out_last_V_U_vld_out);
    regslice_both_out_last_V_U->ack_out(out_r_TREADY);
    regslice_both_out_last_V_U->apdone_blk(regslice_both_out_last_V_U_apdone_blk);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_a_fu_309_p2);
    sensitive << ( icmp_ln947_1_reg_561 );
    sensitive << ( icmp_ln947_fu_304_p2 );

    SC_METHOD(thread_add_ln949_fu_327_p2);
    sensitive << ( trunc_ln944_reg_540 );

    SC_METHOD(thread_add_ln958_fu_294_p2);
    sensitive << ( sub_ln944_reg_533 );

    SC_METHOD(thread_add_ln964_fu_435_p2);
    sensitive << ( select_ln964_reg_621 );
    sensitive << ( sub_ln964_fu_430_p2 );

    SC_METHOD(thread_and_ln949_fu_339_p2);
    sensitive << ( p_Result_7_fu_332_p3 );
    sensitive << ( xor_ln949_fu_321_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( regslice_both_out_data_U_apdone_blk );
    sensitive << ( icmp_ln31_fu_151_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( regslice_both_out_data_U_apdone_blk );
    sensitive << ( icmp_ln31_fu_151_p2 );

    SC_METHOD(thread_bitcast_ln739_fu_463_p1);
    sensitive << ( trunc_ln738_fu_459_p1 );

    SC_METHOD(thread_grp_fu_370_p0);
    sensitive << ( tmp_V_4_reg_515 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_grp_fu_378_p0);
    sensitive << ( tmp_V_4_reg_515 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_grp_fu_378_p1);
    sensitive << ( sub_ln958_reg_571 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_icmp_ln31_fu_151_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( regslice_both_out_data_U_apdone_blk );
    sensitive << ( j3_0_i_reg_140 );

    SC_METHOD(thread_icmp_ln32_fu_163_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( regslice_both_out_data_U_apdone_blk );
    sensitive << ( icmp_ln31_fu_151_p2 );
    sensitive << ( j3_0_i_reg_140 );

    SC_METHOD(thread_icmp_ln935_fu_200_p2);
    sensitive << ( tmp_V_3_reg_493 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_icmp_ln947_1_fu_288_p2);
    sensitive << ( icmp_ln935_reg_510 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( p_Result_10_fu_283_p2 );

    SC_METHOD(thread_icmp_ln947_fu_304_p2);
    sensitive << ( icmp_ln935_reg_510 );
    sensitive << ( tmp_reg_556 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_icmp_ln958_fu_365_p2);
    sensitive << ( icmp_ln935_reg_510 );
    sensitive << ( lsb_index_reg_550 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_j_fu_157_p2);
    sensitive << ( j3_0_i_reg_140 );

    SC_METHOD(thread_l_fu_228_p3);
    sensitive << ( p_Result_13_fu_220_p3 );

    SC_METHOD(thread_last_fu_169_p2);
    sensitive << ( p_read );
    sensitive << ( icmp_ln32_fu_163_p2 );

    SC_METHOD(thread_lsb_index_fu_259_p2);
    sensitive << ( sub_ln944_reg_533 );

    SC_METHOD(thread_lshr_ln947_fu_277_p2);
    sensitive << ( zext_ln947_fu_274_p1 );

    SC_METHOD(thread_m_1_fu_387_p3);
    sensitive << ( icmp_ln958_reg_591 );
    sensitive << ( shl_ln958_reg_606 );
    sensitive << ( zext_ln958_fu_384_p1 );

    SC_METHOD(thread_m_2_fu_396_p2);
    sensitive << ( zext_ln961_fu_393_p1 );
    sensitive << ( m_1_fu_387_p3 );

    SC_METHOD(thread_m_6_fu_427_p1);
    sensitive << ( m_5_reg_611 );

    SC_METHOD(thread_or_ln949_fu_345_p2);
    sensitive << ( and_ln949_fu_339_p2 );
    sensitive << ( a_fu_309_p2 );

    SC_METHOD(thread_or_ln_i_fu_351_p3);
    sensitive << ( or_ln949_fu_345_p2 );

    SC_METHOD(thread_out_r_TDATA_blk_n);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( out_r_TREADY_int );

    SC_METHOD(thread_out_r_TDATA_int);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( icmp_ln935_reg_510 );
    sensitive << ( bitcast_ln739_fu_463_p1 );

    SC_METHOD(thread_out_r_TVALID);
    sensitive << ( regslice_both_out_data_U_vld_out );

    SC_METHOD(thread_out_r_TVALID_int);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( out_r_TREADY_int );

    SC_METHOD(thread_p_Result_10_fu_283_p2);
    sensitive << ( tmp_V_4_reg_515 );
    sensitive << ( lshr_ln947_fu_277_p2 );

    SC_METHOD(thread_p_Result_13_fu_220_p3);
    sensitive << ( p_Result_s_fu_210_p4 );

    SC_METHOD(thread_p_Result_14_fu_447_p5);
    sensitive << ( m_6_fu_427_p1 );
    sensitive << ( tmp_169_i_fu_440_p3 );

    SC_METHOD(thread_p_Result_7_fu_332_p3);
    sensitive << ( tmp_V_4_reg_515 );
    sensitive << ( add_ln949_fu_327_p2 );

    SC_METHOD(thread_p_Result_s_fu_210_p4);
    sensitive << ( tmp_V_4_fu_205_p3 );

    SC_METHOD(thread_select_ln964_fu_420_p3);
    sensitive << ( tmp_23_reg_616 );

    SC_METHOD(thread_sub_ln944_fu_240_p2);
    sensitive << ( l_reg_523 );

    SC_METHOD(thread_sub_ln947_fu_253_p2);
    sensitive << ( trunc_ln947_fu_249_p1 );

    SC_METHOD(thread_sub_ln958_fu_299_p2);
    sensitive << ( sub_ln944_reg_533 );

    SC_METHOD(thread_sub_ln964_fu_430_p2);
    sensitive << ( trunc_ln943_reg_528 );

    SC_METHOD(thread_tmp_169_i_fu_440_p3);
    sensitive << ( p_Result_12_reg_499 );
    sensitive << ( add_ln964_fu_435_p2 );

    SC_METHOD(thread_tmp_22_fu_314_p3);
    sensitive << ( lsb_index_reg_550 );

    SC_METHOD(thread_tmp_V_4_fu_205_p3);
    sensitive << ( tmp_V_3_reg_493 );
    sensitive << ( p_Result_12_reg_499 );
    sensitive << ( tmp_V_reg_505 );

    SC_METHOD(thread_tmp_V_fu_194_p2);
    sensitive << ( tmp_V_3_fu_174_p5 );

    SC_METHOD(thread_trunc_ln738_fu_459_p1);
    sensitive << ( p_Result_14_fu_447_p5 );

    SC_METHOD(thread_trunc_ln943_fu_236_p1);
    sensitive << ( l_fu_228_p3 );

    SC_METHOD(thread_trunc_ln944_fu_245_p1);
    sensitive << ( sub_ln944_fu_240_p2 );

    SC_METHOD(thread_trunc_ln947_fu_249_p1);
    sensitive << ( sub_ln944_fu_240_p2 );

    SC_METHOD(thread_xor_ln949_fu_321_p2);
    sensitive << ( tmp_22_fu_314_p3 );

    SC_METHOD(thread_zext_ln947_fu_274_p1);
    sensitive << ( sub_ln947_reg_545 );

    SC_METHOD(thread_zext_ln958_fu_384_p1);
    sensitive << ( lshr_ln958_reg_601 );

    SC_METHOD(thread_zext_ln961_fu_393_p1);
    sensitive << ( or_ln_i_reg_576 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( regslice_both_out_data_U_apdone_blk );
    sensitive << ( icmp_ln31_fu_151_p2 );
    sensitive << ( out_r_TREADY_int );

    SC_THREAD(thread_ap_var_for_const0);

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "00000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "Loop_2_proc_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, out_r_TDATA, "(port)out_r_TDATA");
    sc_trace(mVcdFile, out_r_TVALID, "(port)out_r_TVALID");
    sc_trace(mVcdFile, out_r_TREADY, "(port)out_r_TREADY");
    sc_trace(mVcdFile, out_r_TLAST, "(port)out_r_TLAST");
    sc_trace(mVcdFile, p_read, "(port)p_read");
    sc_trace(mVcdFile, tmp_data_V_0, "(port)tmp_data_V_0");
    sc_trace(mVcdFile, tmp_data_V_1, "(port)tmp_data_V_1");
    sc_trace(mVcdFile, tmp_data_V_2, "(port)tmp_data_V_2");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, out_r_TDATA_blk_n, "out_r_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, j_fu_157_p2, "j_fu_157_p2");
    sc_trace(mVcdFile, j_reg_483, "j_reg_483");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, regslice_both_out_data_U_apdone_blk, "regslice_both_out_data_U_apdone_blk");
    sc_trace(mVcdFile, last_fu_169_p2, "last_fu_169_p2");
    sc_trace(mVcdFile, last_reg_488, "last_reg_488");
    sc_trace(mVcdFile, icmp_ln31_fu_151_p2, "icmp_ln31_fu_151_p2");
    sc_trace(mVcdFile, tmp_V_3_fu_174_p5, "tmp_V_3_fu_174_p5");
    sc_trace(mVcdFile, tmp_V_3_reg_493, "tmp_V_3_reg_493");
    sc_trace(mVcdFile, p_Result_12_reg_499, "p_Result_12_reg_499");
    sc_trace(mVcdFile, tmp_V_fu_194_p2, "tmp_V_fu_194_p2");
    sc_trace(mVcdFile, tmp_V_reg_505, "tmp_V_reg_505");
    sc_trace(mVcdFile, icmp_ln935_fu_200_p2, "icmp_ln935_fu_200_p2");
    sc_trace(mVcdFile, icmp_ln935_reg_510, "icmp_ln935_reg_510");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_V_4_fu_205_p3, "tmp_V_4_fu_205_p3");
    sc_trace(mVcdFile, tmp_V_4_reg_515, "tmp_V_4_reg_515");
    sc_trace(mVcdFile, l_fu_228_p3, "l_fu_228_p3");
    sc_trace(mVcdFile, l_reg_523, "l_reg_523");
    sc_trace(mVcdFile, trunc_ln943_fu_236_p1, "trunc_ln943_fu_236_p1");
    sc_trace(mVcdFile, trunc_ln943_reg_528, "trunc_ln943_reg_528");
    sc_trace(mVcdFile, sub_ln944_fu_240_p2, "sub_ln944_fu_240_p2");
    sc_trace(mVcdFile, sub_ln944_reg_533, "sub_ln944_reg_533");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, trunc_ln944_fu_245_p1, "trunc_ln944_fu_245_p1");
    sc_trace(mVcdFile, trunc_ln944_reg_540, "trunc_ln944_reg_540");
    sc_trace(mVcdFile, sub_ln947_fu_253_p2, "sub_ln947_fu_253_p2");
    sc_trace(mVcdFile, sub_ln947_reg_545, "sub_ln947_reg_545");
    sc_trace(mVcdFile, lsb_index_fu_259_p2, "lsb_index_fu_259_p2");
    sc_trace(mVcdFile, lsb_index_reg_550, "lsb_index_reg_550");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, tmp_reg_556, "tmp_reg_556");
    sc_trace(mVcdFile, icmp_ln947_1_fu_288_p2, "icmp_ln947_1_fu_288_p2");
    sc_trace(mVcdFile, icmp_ln947_1_reg_561, "icmp_ln947_1_reg_561");
    sc_trace(mVcdFile, add_ln958_fu_294_p2, "add_ln958_fu_294_p2");
    sc_trace(mVcdFile, add_ln958_reg_566, "add_ln958_reg_566");
    sc_trace(mVcdFile, sub_ln958_fu_299_p2, "sub_ln958_fu_299_p2");
    sc_trace(mVcdFile, sub_ln958_reg_571, "sub_ln958_reg_571");
    sc_trace(mVcdFile, or_ln_i_fu_351_p3, "or_ln_i_fu_351_p3");
    sc_trace(mVcdFile, or_ln_i_reg_576, "or_ln_i_reg_576");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, icmp_ln958_fu_365_p2, "icmp_ln958_fu_365_p2");
    sc_trace(mVcdFile, icmp_ln958_reg_591, "icmp_ln958_reg_591");
    sc_trace(mVcdFile, grp_fu_370_p2, "grp_fu_370_p2");
    sc_trace(mVcdFile, lshr_ln958_reg_601, "lshr_ln958_reg_601");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, grp_fu_378_p2, "grp_fu_378_p2");
    sc_trace(mVcdFile, shl_ln958_reg_606, "shl_ln958_reg_606");
    sc_trace(mVcdFile, m_5_reg_611, "m_5_reg_611");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, tmp_23_reg_616, "tmp_23_reg_616");
    sc_trace(mVcdFile, select_ln964_fu_420_p3, "select_ln964_fu_420_p3");
    sc_trace(mVcdFile, select_ln964_reg_621, "select_ln964_reg_621");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, j3_0_i_reg_140, "j3_0_i_reg_140");
    sc_trace(mVcdFile, icmp_ln32_fu_163_p2, "icmp_ln32_fu_163_p2");
    sc_trace(mVcdFile, p_Result_s_fu_210_p4, "p_Result_s_fu_210_p4");
    sc_trace(mVcdFile, p_Result_13_fu_220_p3, "p_Result_13_fu_220_p3");
    sc_trace(mVcdFile, trunc_ln947_fu_249_p1, "trunc_ln947_fu_249_p1");
    sc_trace(mVcdFile, zext_ln947_fu_274_p1, "zext_ln947_fu_274_p1");
    sc_trace(mVcdFile, lshr_ln947_fu_277_p2, "lshr_ln947_fu_277_p2");
    sc_trace(mVcdFile, p_Result_10_fu_283_p2, "p_Result_10_fu_283_p2");
    sc_trace(mVcdFile, icmp_ln947_fu_304_p2, "icmp_ln947_fu_304_p2");
    sc_trace(mVcdFile, tmp_22_fu_314_p3, "tmp_22_fu_314_p3");
    sc_trace(mVcdFile, add_ln949_fu_327_p2, "add_ln949_fu_327_p2");
    sc_trace(mVcdFile, p_Result_7_fu_332_p3, "p_Result_7_fu_332_p3");
    sc_trace(mVcdFile, xor_ln949_fu_321_p2, "xor_ln949_fu_321_p2");
    sc_trace(mVcdFile, and_ln949_fu_339_p2, "and_ln949_fu_339_p2");
    sc_trace(mVcdFile, a_fu_309_p2, "a_fu_309_p2");
    sc_trace(mVcdFile, or_ln949_fu_345_p2, "or_ln949_fu_345_p2");
    sc_trace(mVcdFile, grp_fu_370_p0, "grp_fu_370_p0");
    sc_trace(mVcdFile, grp_fu_378_p0, "grp_fu_378_p0");
    sc_trace(mVcdFile, grp_fu_378_p1, "grp_fu_378_p1");
    sc_trace(mVcdFile, zext_ln958_fu_384_p1, "zext_ln958_fu_384_p1");
    sc_trace(mVcdFile, zext_ln961_fu_393_p1, "zext_ln961_fu_393_p1");
    sc_trace(mVcdFile, m_1_fu_387_p3, "m_1_fu_387_p3");
    sc_trace(mVcdFile, m_2_fu_396_p2, "m_2_fu_396_p2");
    sc_trace(mVcdFile, sub_ln964_fu_430_p2, "sub_ln964_fu_430_p2");
    sc_trace(mVcdFile, add_ln964_fu_435_p2, "add_ln964_fu_435_p2");
    sc_trace(mVcdFile, m_6_fu_427_p1, "m_6_fu_427_p1");
    sc_trace(mVcdFile, tmp_169_i_fu_440_p3, "tmp_169_i_fu_440_p3");
    sc_trace(mVcdFile, p_Result_14_fu_447_p5, "p_Result_14_fu_447_p5");
    sc_trace(mVcdFile, trunc_ln738_fu_459_p1, "trunc_ln738_fu_459_p1");
    sc_trace(mVcdFile, bitcast_ln739_fu_463_p1, "bitcast_ln739_fu_463_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, out_r_TDATA_int, "out_r_TDATA_int");
    sc_trace(mVcdFile, out_r_TVALID_int, "out_r_TVALID_int");
    sc_trace(mVcdFile, out_r_TREADY_int, "out_r_TREADY_int");
    sc_trace(mVcdFile, regslice_both_out_data_U_vld_out, "regslice_both_out_data_U_vld_out");
    sc_trace(mVcdFile, regslice_both_out_last_V_U_apdone_blk, "regslice_both_out_last_V_U_apdone_blk");
    sc_trace(mVcdFile, regslice_both_out_last_V_U_ack_in_dummy, "regslice_both_out_last_V_U_ack_in_dummy");
    sc_trace(mVcdFile, regslice_both_out_last_V_U_vld_out, "regslice_both_out_last_V_U_vld_out");
#endif

    }
}

Loop_2_proc::~Loop_2_proc() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete myproject_axi_mux_32_20_1_1_U585;
    delete myproject_axi_lshr_32ns_32ns_32_2_1_U586;
    delete myproject_axi_shl_64ns_32ns_64_2_1_U587;
    delete regslice_both_out_data_U;
    delete regslice_both_out_last_V_U;
}

void Loop_2_proc::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void Loop_2_proc::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(regslice_both_out_data_U_apdone_blk.read(), ap_const_logic_0) && 
                    esl_seteq<1,1,1>(icmp_ln31_fu_151_p2.read(), ap_const_lv1_1))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(out_r_TREADY_int.read(), ap_const_logic_1))) {
        j3_0_i_reg_140 = j_reg_483.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        j3_0_i_reg_140 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln935_reg_510.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        add_ln958_reg_566 = add_ln958_fu_294_p2.read();
        icmp_ln947_1_reg_561 = icmp_ln947_1_fu_288_p2.read();
        lsb_index_reg_550 = lsb_index_fu_259_p2.read();
        sub_ln958_reg_571 = sub_ln958_fu_299_p2.read();
        tmp_reg_556 = lsb_index_fu_259_p2.read().range(31, 1);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        icmp_ln935_reg_510 = icmp_ln935_fu_200_p2.read();
        l_reg_523 = l_fu_228_p3.read();
        tmp_V_4_reg_515 = tmp_V_4_fu_205_p3.read();
        trunc_ln943_reg_528 = trunc_ln943_fu_236_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln935_reg_510.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        icmp_ln958_reg_591 = icmp_ln958_fu_365_p2.read();
        or_ln_i_reg_576 = or_ln_i_fu_351_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(regslice_both_out_data_U_apdone_blk.read(), ap_const_logic_0))) {
        j_reg_483 = j_fu_157_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(regslice_both_out_data_U_apdone_blk.read(), ap_const_logic_0) && esl_seteq<1,1,1>(icmp_ln31_fu_151_p2.read(), ap_const_lv1_0))) {
        last_reg_488 = last_fu_169_p2.read();
        p_Result_12_reg_499 = tmp_V_3_fu_174_p5.read().range(19, 19);
        tmp_V_3_reg_493 = tmp_V_3_fu_174_p5.read();
        tmp_V_reg_505 = tmp_V_fu_194_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln935_reg_510.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        lshr_ln958_reg_601 = grp_fu_370_p2.read();
        shl_ln958_reg_606 = grp_fu_378_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln935_reg_510.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        m_5_reg_611 = m_2_fu_396_p2.read().range(63, 1);
        tmp_23_reg_616 = m_2_fu_396_p2.read().range(25, 25);
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln935_reg_510.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        select_ln964_reg_621 = select_ln964_fu_420_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln935_reg_510.read()))) {
        sub_ln944_reg_533 = sub_ln944_fu_240_p2.read();
        sub_ln947_reg_545 = sub_ln947_fu_253_p2.read();
        trunc_ln944_reg_540 = trunc_ln944_fu_245_p1.read();
    }
}

void Loop_2_proc::thread_a_fu_309_p2() {
    a_fu_309_p2 = (icmp_ln947_fu_304_p2.read() & icmp_ln947_1_reg_561.read());
}

void Loop_2_proc::thread_add_ln949_fu_327_p2() {
    add_ln949_fu_327_p2 = (!ap_const_lv20_FFFE8.is_01() || !trunc_ln944_reg_540.read().is_01())? sc_lv<20>(): (sc_bigint<20>(ap_const_lv20_FFFE8) + sc_biguint<20>(trunc_ln944_reg_540.read()));
}

void Loop_2_proc::thread_add_ln958_fu_294_p2() {
    add_ln958_fu_294_p2 = (!ap_const_lv32_FFFFFFE7.is_01() || !sub_ln944_reg_533.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_FFFFFFE7) + sc_biguint<32>(sub_ln944_reg_533.read()));
}

void Loop_2_proc::thread_add_ln964_fu_435_p2() {
    add_ln964_fu_435_p2 = (!sub_ln964_fu_430_p2.read().is_01() || !select_ln964_reg_621.read().is_01())? sc_lv<8>(): (sc_biguint<8>(sub_ln964_fu_430_p2.read()) + sc_biguint<8>(select_ln964_reg_621.read()));
}

void Loop_2_proc::thread_and_ln949_fu_339_p2() {
    and_ln949_fu_339_p2 = (p_Result_7_fu_332_p3.read() & xor_ln949_fu_321_p2.read());
}

void Loop_2_proc::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void Loop_2_proc::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void Loop_2_proc::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void Loop_2_proc::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void Loop_2_proc::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void Loop_2_proc::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void Loop_2_proc::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void Loop_2_proc::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void Loop_2_proc::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void Loop_2_proc::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void Loop_2_proc::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void Loop_2_proc::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void Loop_2_proc::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(regslice_both_out_data_U_apdone_blk.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(icmp_ln31_fu_151_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void Loop_2_proc::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void Loop_2_proc::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(regslice_both_out_data_U_apdone_blk.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(icmp_ln31_fu_151_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void Loop_2_proc::thread_bitcast_ln739_fu_463_p1() {
    bitcast_ln739_fu_463_p1 = trunc_ln738_fu_459_p1.read();
}

void Loop_2_proc::thread_grp_fu_370_p0() {
    grp_fu_370_p0 = esl_zext<32,20>(tmp_V_4_reg_515.read());
}

void Loop_2_proc::thread_grp_fu_378_p0() {
    grp_fu_378_p0 = esl_zext<64,20>(tmp_V_4_reg_515.read());
}

void Loop_2_proc::thread_grp_fu_378_p1() {
    grp_fu_378_p1 = esl_zext<64,32>(sub_ln958_reg_571.read());
}

void Loop_2_proc::thread_icmp_ln31_fu_151_p2() {
    icmp_ln31_fu_151_p2 = (!j3_0_i_reg_140.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(j3_0_i_reg_140.read() == ap_const_lv2_3);
}

void Loop_2_proc::thread_icmp_ln32_fu_163_p2() {
    icmp_ln32_fu_163_p2 = (!j3_0_i_reg_140.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(j3_0_i_reg_140.read() == ap_const_lv2_2);
}

void Loop_2_proc::thread_icmp_ln935_fu_200_p2() {
    icmp_ln935_fu_200_p2 = (!tmp_V_3_reg_493.read().is_01() || !ap_const_lv20_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_V_3_reg_493.read() == ap_const_lv20_0);
}

void Loop_2_proc::thread_icmp_ln947_1_fu_288_p2() {
    icmp_ln947_1_fu_288_p2 = (!p_Result_10_fu_283_p2.read().is_01() || !ap_const_lv20_0.is_01())? sc_lv<1>(): sc_lv<1>(p_Result_10_fu_283_p2.read() != ap_const_lv20_0);
}

void Loop_2_proc::thread_icmp_ln947_fu_304_p2() {
    icmp_ln947_fu_304_p2 = (!tmp_reg_556.read().is_01() || !ap_const_lv31_0.is_01())? sc_lv<1>(): (sc_bigint<31>(tmp_reg_556.read()) > sc_bigint<31>(ap_const_lv31_0));
}

void Loop_2_proc::thread_icmp_ln958_fu_365_p2() {
    icmp_ln958_fu_365_p2 = (!lsb_index_reg_550.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(lsb_index_reg_550.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void Loop_2_proc::thread_j_fu_157_p2() {
    j_fu_157_p2 = (!j3_0_i_reg_140.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(j3_0_i_reg_140.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void Loop_2_proc::thread_l_fu_228_p3() {
    l_fu_228_p3 = esl_cttz<32,32>(p_Result_13_fu_220_p3.read());
}

void Loop_2_proc::thread_last_fu_169_p2() {
    last_fu_169_p2 = (icmp_ln32_fu_163_p2.read() & p_read.read());
}

void Loop_2_proc::thread_lsb_index_fu_259_p2() {
    lsb_index_fu_259_p2 = (!ap_const_lv32_FFFFFFE8.is_01() || !sub_ln944_reg_533.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_FFFFFFE8) + sc_biguint<32>(sub_ln944_reg_533.read()));
}

void Loop_2_proc::thread_lshr_ln947_fu_277_p2() {
    lshr_ln947_fu_277_p2 = (!zext_ln947_fu_274_p1.read().is_01())? sc_lv<20>(): ap_const_lv20_FFFFF >> (unsigned short)zext_ln947_fu_274_p1.read().to_uint();
}

void Loop_2_proc::thread_m_1_fu_387_p3() {
    m_1_fu_387_p3 = (!icmp_ln958_reg_591.read()[0].is_01())? sc_lv<64>(): ((icmp_ln958_reg_591.read()[0].to_bool())? zext_ln958_fu_384_p1.read(): shl_ln958_reg_606.read());
}

void Loop_2_proc::thread_m_2_fu_396_p2() {
    m_2_fu_396_p2 = (!zext_ln961_fu_393_p1.read().is_01() || !m_1_fu_387_p3.read().is_01())? sc_lv<64>(): (sc_biguint<64>(zext_ln961_fu_393_p1.read()) + sc_biguint<64>(m_1_fu_387_p3.read()));
}

void Loop_2_proc::thread_m_6_fu_427_p1() {
    m_6_fu_427_p1 = esl_zext<64,63>(m_5_reg_611.read());
}

void Loop_2_proc::thread_or_ln949_fu_345_p2() {
    or_ln949_fu_345_p2 = (and_ln949_fu_339_p2.read() | a_fu_309_p2.read());
}

void Loop_2_proc::thread_or_ln_i_fu_351_p3() {
    or_ln_i_fu_351_p3 = esl_concat<31,1>(ap_const_lv31_0, or_ln949_fu_345_p2.read());
}

void Loop_2_proc::thread_out_r_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()))) {
        out_r_TDATA_blk_n = out_r_TREADY_int.read();
    } else {
        out_r_TDATA_blk_n = ap_const_logic_1;
    }
}

void Loop_2_proc::thread_out_r_TDATA_int() {
    out_r_TDATA_int = (!icmp_ln935_reg_510.read()[0].is_01())? sc_lv<32>(): ((icmp_ln935_reg_510.read()[0].to_bool())? ap_const_lv32_0: bitcast_ln739_fu_463_p1.read());
}

void Loop_2_proc::thread_out_r_TVALID() {
    out_r_TVALID = regslice_both_out_data_U_vld_out.read();
}

void Loop_2_proc::thread_out_r_TVALID_int() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
         esl_seteq<1,1,1>(out_r_TREADY_int.read(), ap_const_logic_1))) {
        out_r_TVALID_int = ap_const_logic_1;
    } else {
        out_r_TVALID_int = ap_const_logic_0;
    }
}

void Loop_2_proc::thread_p_Result_10_fu_283_p2() {
    p_Result_10_fu_283_p2 = (tmp_V_4_reg_515.read() & lshr_ln947_fu_277_p2.read());
}

void Loop_2_proc::thread_p_Result_13_fu_220_p3() {
    p_Result_13_fu_220_p3 = esl_concat<12,20>(ap_const_lv12_FFF, p_Result_s_fu_210_p4.read());
}

void Loop_2_proc::thread_p_Result_14_fu_447_p5() {
    p_Result_14_fu_447_p5 = esl_partset<64,64,9,32,32>(m_6_fu_427_p1.read(), tmp_169_i_fu_440_p3.read(), ap_const_lv32_17, ap_const_lv32_1F);
}

void Loop_2_proc::thread_p_Result_7_fu_332_p3() {
    p_Result_7_fu_332_p3 = (!add_ln949_fu_327_p2.read().is_01() || sc_biguint<20>(add_ln949_fu_327_p2.read()).to_uint() >= 20)? sc_lv<1>(): tmp_V_4_reg_515.read().range(sc_biguint<20>(add_ln949_fu_327_p2.read()).to_uint(), sc_biguint<20>(add_ln949_fu_327_p2.read()).to_uint());
}

void Loop_2_proc::thread_p_Result_s_fu_210_p4() {
    p_Result_s_fu_210_p4 = tmp_V_4_fu_205_p3.read().range(0, 19);
}

void Loop_2_proc::thread_select_ln964_fu_420_p3() {
    select_ln964_fu_420_p3 = (!tmp_23_reg_616.read()[0].is_01())? sc_lv<8>(): ((tmp_23_reg_616.read()[0].to_bool())? ap_const_lv8_7F: ap_const_lv8_7E);
}

void Loop_2_proc::thread_sub_ln944_fu_240_p2() {
    sub_ln944_fu_240_p2 = (!ap_const_lv32_14.is_01() || !l_reg_523.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_14) - sc_biguint<32>(l_reg_523.read()));
}

void Loop_2_proc::thread_sub_ln947_fu_253_p2() {
    sub_ln947_fu_253_p2 = (!ap_const_lv5_D.is_01() || !trunc_ln947_fu_249_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(ap_const_lv5_D) - sc_biguint<5>(trunc_ln947_fu_249_p1.read()));
}

void Loop_2_proc::thread_sub_ln958_fu_299_p2() {
    sub_ln958_fu_299_p2 = (!ap_const_lv32_19.is_01() || !sub_ln944_reg_533.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_19) - sc_biguint<32>(sub_ln944_reg_533.read()));
}

void Loop_2_proc::thread_sub_ln964_fu_430_p2() {
    sub_ln964_fu_430_p2 = (!ap_const_lv8_8.is_01() || !trunc_ln943_reg_528.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_8) - sc_biguint<8>(trunc_ln943_reg_528.read()));
}

void Loop_2_proc::thread_tmp_169_i_fu_440_p3() {
    tmp_169_i_fu_440_p3 = esl_concat<1,8>(p_Result_12_reg_499.read(), add_ln964_fu_435_p2.read());
}

void Loop_2_proc::thread_tmp_22_fu_314_p3() {
    tmp_22_fu_314_p3 = lsb_index_reg_550.read().range(31, 31);
}

void Loop_2_proc::thread_tmp_V_4_fu_205_p3() {
    tmp_V_4_fu_205_p3 = (!p_Result_12_reg_499.read()[0].is_01())? sc_lv<20>(): ((p_Result_12_reg_499.read()[0].to_bool())? tmp_V_reg_505.read(): tmp_V_3_reg_493.read());
}

void Loop_2_proc::thread_tmp_V_fu_194_p2() {
    tmp_V_fu_194_p2 = (!ap_const_lv20_0.is_01() || !tmp_V_3_fu_174_p5.read().is_01())? sc_lv<20>(): (sc_biguint<20>(ap_const_lv20_0) - sc_biguint<20>(tmp_V_3_fu_174_p5.read()));
}

void Loop_2_proc::thread_trunc_ln738_fu_459_p1() {
    trunc_ln738_fu_459_p1 = p_Result_14_fu_447_p5.read().range(32-1, 0);
}

void Loop_2_proc::thread_trunc_ln943_fu_236_p1() {
    trunc_ln943_fu_236_p1 = l_fu_228_p3.read().range(8-1, 0);
}

void Loop_2_proc::thread_trunc_ln944_fu_245_p1() {
    trunc_ln944_fu_245_p1 = sub_ln944_fu_240_p2.read().range(20-1, 0);
}

void Loop_2_proc::thread_trunc_ln947_fu_249_p1() {
    trunc_ln947_fu_249_p1 = sub_ln944_fu_240_p2.read().range(5-1, 0);
}

void Loop_2_proc::thread_xor_ln949_fu_321_p2() {
    xor_ln949_fu_321_p2 = (tmp_22_fu_314_p3.read() ^ ap_const_lv1_1);
}

void Loop_2_proc::thread_zext_ln947_fu_274_p1() {
    zext_ln947_fu_274_p1 = esl_zext<20,5>(sub_ln947_reg_545.read());
}

void Loop_2_proc::thread_zext_ln958_fu_384_p1() {
    zext_ln958_fu_384_p1 = esl_zext<64,32>(lshr_ln958_reg_601.read());
}

void Loop_2_proc::thread_zext_ln961_fu_393_p1() {
    zext_ln961_fu_393_p1 = esl_zext<64,32>(or_ln_i_reg_576.read());
}

void Loop_2_proc::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(regslice_both_out_data_U_apdone_blk.read(), ap_const_logic_0) && esl_seteq<1,1,1>(icmp_ln31_fu_151_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(regslice_both_out_data_U_apdone_blk.read(), ap_const_logic_0) && esl_seteq<1,1,1>(icmp_ln31_fu_151_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && esl_seteq<1,1,1>(out_r_TREADY_int.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state11;
            } else {
                ap_NS_fsm = ap_ST_fsm_state10;
            }
            break;
        case 1024 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(out_r_TREADY_int.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state11;
            }
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXXXX";
            break;
    }
}

}

