// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::ap_ST_fsm_pp0_stage0 = "1";
const bool relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::ap_const_boolean_1 = true;
const sc_lv<32> relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::ap_const_boolean_0 = false;
const sc_lv<20> relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::ap_const_lv20_0 = "00000000000000000000";

relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( io_acc_block_signal_op4 );
    sensitive << ( io_acc_block_signal_op88 );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( io_acc_block_signal_op4 );
    sensitive << ( io_acc_block_signal_op88 );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( io_acc_block_signal_op4 );
    sensitive << ( io_acc_block_signal_op88 );

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( io_acc_block_signal_op4 );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2);
    sensitive << ( io_acc_block_signal_op88 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_reg_pp0_iter0);
    sensitive << ( real_start );

    SC_METHOD(thread_ap_idle);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_ap_idle_pp0_0to1);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( internal_ap_ready );

    SC_METHOD(thread_ap_reset_idle_pp0);
    sensitive << ( real_start );
    sensitive << ( ap_idle_pp0_0to1 );

    SC_METHOD(thread_data_V_data_0_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( data_V_data_0_V_empty_n );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_data_V_data_0_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_data_V_data_10_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( data_V_data_10_V_empty_n );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_data_V_data_10_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_data_V_data_11_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( data_V_data_11_V_empty_n );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_data_V_data_11_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_data_V_data_12_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( data_V_data_12_V_empty_n );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_data_V_data_12_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_data_V_data_13_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( data_V_data_13_V_empty_n );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_data_V_data_13_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_data_V_data_14_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( data_V_data_14_V_empty_n );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_data_V_data_14_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_data_V_data_15_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( data_V_data_15_V_empty_n );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_data_V_data_15_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_data_V_data_1_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( data_V_data_1_V_empty_n );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_data_V_data_1_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_data_V_data_2_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( data_V_data_2_V_empty_n );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_data_V_data_2_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_data_V_data_3_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( data_V_data_3_V_empty_n );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_data_V_data_3_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_data_V_data_4_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( data_V_data_4_V_empty_n );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_data_V_data_4_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_data_V_data_5_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( data_V_data_5_V_empty_n );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_data_V_data_5_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_data_V_data_6_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( data_V_data_6_V_empty_n );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_data_V_data_6_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_data_V_data_7_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( data_V_data_7_V_empty_n );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_data_V_data_7_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_data_V_data_8_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( data_V_data_8_V_empty_n );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_data_V_data_8_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_data_V_data_9_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( data_V_data_9_V_empty_n );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_data_V_data_9_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_icmp_ln1494_10_fu_300_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_data_V_10_reg_502 );

    SC_METHOD(thread_icmp_ln1494_11_fu_305_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_data_V_11_reg_508 );

    SC_METHOD(thread_icmp_ln1494_12_fu_310_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_data_V_12_reg_514 );

    SC_METHOD(thread_icmp_ln1494_13_fu_315_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_data_V_13_reg_520 );

    SC_METHOD(thread_icmp_ln1494_14_fu_320_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_data_V_14_reg_526 );

    SC_METHOD(thread_icmp_ln1494_15_fu_325_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_data_V_15_reg_532 );

    SC_METHOD(thread_icmp_ln1494_1_fu_255_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_data_V_1_reg_448 );

    SC_METHOD(thread_icmp_ln1494_2_fu_260_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_data_V_2_reg_454 );

    SC_METHOD(thread_icmp_ln1494_3_fu_265_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_data_V_3_reg_460 );

    SC_METHOD(thread_icmp_ln1494_4_fu_270_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_data_V_4_reg_466 );

    SC_METHOD(thread_icmp_ln1494_5_fu_275_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_data_V_5_reg_472 );

    SC_METHOD(thread_icmp_ln1494_6_fu_280_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_data_V_624_reg_478 );

    SC_METHOD(thread_icmp_ln1494_7_fu_285_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_data_V_7_reg_484 );

    SC_METHOD(thread_icmp_ln1494_8_fu_290_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_data_V_8_reg_490 );

    SC_METHOD(thread_icmp_ln1494_9_fu_295_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_data_V_9_reg_496 );

    SC_METHOD(thread_icmp_ln1494_fu_250_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_data_V_0_reg_442 );

    SC_METHOD(thread_internal_ap_ready);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_io_acc_block_signal_op4);
    sensitive << ( data_V_data_0_V_empty_n );
    sensitive << ( data_V_data_1_V_empty_n );
    sensitive << ( data_V_data_2_V_empty_n );
    sensitive << ( data_V_data_3_V_empty_n );
    sensitive << ( data_V_data_4_V_empty_n );
    sensitive << ( data_V_data_5_V_empty_n );
    sensitive << ( data_V_data_6_V_empty_n );
    sensitive << ( data_V_data_7_V_empty_n );
    sensitive << ( data_V_data_8_V_empty_n );
    sensitive << ( data_V_data_9_V_empty_n );
    sensitive << ( data_V_data_10_V_empty_n );
    sensitive << ( data_V_data_11_V_empty_n );
    sensitive << ( data_V_data_12_V_empty_n );
    sensitive << ( data_V_data_13_V_empty_n );
    sensitive << ( data_V_data_14_V_empty_n );
    sensitive << ( data_V_data_15_V_empty_n );

    SC_METHOD(thread_io_acc_block_signal_op88);
    sensitive << ( res_V_data_0_V_full_n );
    sensitive << ( res_V_data_1_V_full_n );
    sensitive << ( res_V_data_2_V_full_n );
    sensitive << ( res_V_data_3_V_full_n );
    sensitive << ( res_V_data_4_V_full_n );
    sensitive << ( res_V_data_5_V_full_n );
    sensitive << ( res_V_data_6_V_full_n );
    sensitive << ( res_V_data_7_V_full_n );
    sensitive << ( res_V_data_8_V_full_n );
    sensitive << ( res_V_data_9_V_full_n );
    sensitive << ( res_V_data_10_V_full_n );
    sensitive << ( res_V_data_11_V_full_n );
    sensitive << ( res_V_data_12_V_full_n );
    sensitive << ( res_V_data_13_V_full_n );
    sensitive << ( res_V_data_14_V_full_n );
    sensitive << ( res_V_data_15_V_full_n );

    SC_METHOD(thread_real_start);
    sensitive << ( ap_start );
    sensitive << ( start_full_n );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_res_V_data_0_V_blk_n);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( res_V_data_0_V_full_n );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_res_V_data_0_V_din);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_data_0_V_reg_538 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_res_V_data_0_V_write);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_V_data_10_V_blk_n);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( res_V_data_10_V_full_n );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_res_V_data_10_V_din);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_data_10_V_reg_588 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_res_V_data_10_V_write);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_V_data_11_V_blk_n);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( res_V_data_11_V_full_n );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_res_V_data_11_V_din);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_data_11_V_reg_593 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_res_V_data_11_V_write);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_V_data_12_V_blk_n);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( res_V_data_12_V_full_n );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_res_V_data_12_V_din);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_data_12_V_reg_598 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_res_V_data_12_V_write);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_V_data_13_V_blk_n);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( res_V_data_13_V_full_n );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_res_V_data_13_V_din);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_data_13_V_reg_603 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_res_V_data_13_V_write);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_V_data_14_V_blk_n);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( res_V_data_14_V_full_n );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_res_V_data_14_V_din);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_data_14_V_reg_608 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_res_V_data_14_V_write);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_V_data_15_V_blk_n);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( res_V_data_15_V_full_n );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_res_V_data_15_V_din);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_data_15_V_reg_613 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_res_V_data_15_V_write);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_V_data_1_V_blk_n);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( res_V_data_1_V_full_n );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_res_V_data_1_V_din);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_data_1_V_reg_543 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_res_V_data_1_V_write);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_V_data_2_V_blk_n);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( res_V_data_2_V_full_n );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_res_V_data_2_V_din);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_data_2_V_reg_548 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_res_V_data_2_V_write);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_V_data_3_V_blk_n);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( res_V_data_3_V_full_n );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_res_V_data_3_V_din);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_data_3_V_reg_553 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_res_V_data_3_V_write);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_V_data_4_V_blk_n);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( res_V_data_4_V_full_n );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_res_V_data_4_V_din);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_data_4_V_reg_558 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_res_V_data_4_V_write);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_V_data_5_V_blk_n);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( res_V_data_5_V_full_n );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_res_V_data_5_V_din);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_data_5_V_reg_563 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_res_V_data_5_V_write);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_V_data_6_V_blk_n);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( res_V_data_6_V_full_n );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_res_V_data_6_V_din);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_data_6_V_reg_568 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_res_V_data_6_V_write);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_V_data_7_V_blk_n);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( res_V_data_7_V_full_n );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_res_V_data_7_V_din);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_data_7_V_reg_573 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_res_V_data_7_V_write);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_V_data_8_V_blk_n);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( res_V_data_8_V_full_n );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_res_V_data_8_V_din);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_data_8_V_reg_578 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_res_V_data_8_V_write);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_V_data_9_V_blk_n);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( res_V_data_9_V_full_n );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_res_V_data_9_V_din);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_data_9_V_reg_583 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_res_V_data_9_V_write);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_start_out);
    sensitive << ( real_start );

    SC_METHOD(thread_start_write);
    sensitive << ( real_start );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_tmp_data_0_V_fu_330_p3);
    sensitive << ( tmp_data_V_0_reg_442 );
    sensitive << ( icmp_ln1494_fu_250_p2 );

    SC_METHOD(thread_tmp_data_10_V_fu_400_p3);
    sensitive << ( tmp_data_V_10_reg_502 );
    sensitive << ( icmp_ln1494_10_fu_300_p2 );

    SC_METHOD(thread_tmp_data_11_V_fu_407_p3);
    sensitive << ( tmp_data_V_11_reg_508 );
    sensitive << ( icmp_ln1494_11_fu_305_p2 );

    SC_METHOD(thread_tmp_data_12_V_fu_414_p3);
    sensitive << ( tmp_data_V_12_reg_514 );
    sensitive << ( icmp_ln1494_12_fu_310_p2 );

    SC_METHOD(thread_tmp_data_13_V_fu_421_p3);
    sensitive << ( tmp_data_V_13_reg_520 );
    sensitive << ( icmp_ln1494_13_fu_315_p2 );

    SC_METHOD(thread_tmp_data_14_V_fu_428_p3);
    sensitive << ( tmp_data_V_14_reg_526 );
    sensitive << ( icmp_ln1494_14_fu_320_p2 );

    SC_METHOD(thread_tmp_data_15_V_fu_435_p3);
    sensitive << ( tmp_data_V_15_reg_532 );
    sensitive << ( icmp_ln1494_15_fu_325_p2 );

    SC_METHOD(thread_tmp_data_1_V_fu_337_p3);
    sensitive << ( tmp_data_V_1_reg_448 );
    sensitive << ( icmp_ln1494_1_fu_255_p2 );

    SC_METHOD(thread_tmp_data_2_V_fu_344_p3);
    sensitive << ( tmp_data_V_2_reg_454 );
    sensitive << ( icmp_ln1494_2_fu_260_p2 );

    SC_METHOD(thread_tmp_data_3_V_fu_351_p3);
    sensitive << ( tmp_data_V_3_reg_460 );
    sensitive << ( icmp_ln1494_3_fu_265_p2 );

    SC_METHOD(thread_tmp_data_4_V_fu_358_p3);
    sensitive << ( tmp_data_V_4_reg_466 );
    sensitive << ( icmp_ln1494_4_fu_270_p2 );

    SC_METHOD(thread_tmp_data_5_V_fu_365_p3);
    sensitive << ( tmp_data_V_5_reg_472 );
    sensitive << ( icmp_ln1494_5_fu_275_p2 );

    SC_METHOD(thread_tmp_data_6_V_fu_372_p3);
    sensitive << ( tmp_data_V_624_reg_478 );
    sensitive << ( icmp_ln1494_6_fu_280_p2 );

    SC_METHOD(thread_tmp_data_7_V_fu_379_p3);
    sensitive << ( tmp_data_V_7_reg_484 );
    sensitive << ( icmp_ln1494_7_fu_285_p2 );

    SC_METHOD(thread_tmp_data_8_V_fu_386_p3);
    sensitive << ( tmp_data_V_8_reg_490 );
    sensitive << ( icmp_ln1494_8_fu_290_p2 );

    SC_METHOD(thread_tmp_data_9_V_fu_393_p3);
    sensitive << ( tmp_data_V_9_reg_496 );
    sensitive << ( icmp_ln1494_9_fu_295_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_reset_idle_pp0 );

    start_once_reg = SC_LOGIC_0;
    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "1";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, start_full_n, "(port)start_full_n");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, data_V_data_0_V_dout, "(port)data_V_data_0_V_dout");
    sc_trace(mVcdFile, data_V_data_0_V_empty_n, "(port)data_V_data_0_V_empty_n");
    sc_trace(mVcdFile, data_V_data_0_V_read, "(port)data_V_data_0_V_read");
    sc_trace(mVcdFile, data_V_data_1_V_dout, "(port)data_V_data_1_V_dout");
    sc_trace(mVcdFile, data_V_data_1_V_empty_n, "(port)data_V_data_1_V_empty_n");
    sc_trace(mVcdFile, data_V_data_1_V_read, "(port)data_V_data_1_V_read");
    sc_trace(mVcdFile, data_V_data_2_V_dout, "(port)data_V_data_2_V_dout");
    sc_trace(mVcdFile, data_V_data_2_V_empty_n, "(port)data_V_data_2_V_empty_n");
    sc_trace(mVcdFile, data_V_data_2_V_read, "(port)data_V_data_2_V_read");
    sc_trace(mVcdFile, data_V_data_3_V_dout, "(port)data_V_data_3_V_dout");
    sc_trace(mVcdFile, data_V_data_3_V_empty_n, "(port)data_V_data_3_V_empty_n");
    sc_trace(mVcdFile, data_V_data_3_V_read, "(port)data_V_data_3_V_read");
    sc_trace(mVcdFile, data_V_data_4_V_dout, "(port)data_V_data_4_V_dout");
    sc_trace(mVcdFile, data_V_data_4_V_empty_n, "(port)data_V_data_4_V_empty_n");
    sc_trace(mVcdFile, data_V_data_4_V_read, "(port)data_V_data_4_V_read");
    sc_trace(mVcdFile, data_V_data_5_V_dout, "(port)data_V_data_5_V_dout");
    sc_trace(mVcdFile, data_V_data_5_V_empty_n, "(port)data_V_data_5_V_empty_n");
    sc_trace(mVcdFile, data_V_data_5_V_read, "(port)data_V_data_5_V_read");
    sc_trace(mVcdFile, data_V_data_6_V_dout, "(port)data_V_data_6_V_dout");
    sc_trace(mVcdFile, data_V_data_6_V_empty_n, "(port)data_V_data_6_V_empty_n");
    sc_trace(mVcdFile, data_V_data_6_V_read, "(port)data_V_data_6_V_read");
    sc_trace(mVcdFile, data_V_data_7_V_dout, "(port)data_V_data_7_V_dout");
    sc_trace(mVcdFile, data_V_data_7_V_empty_n, "(port)data_V_data_7_V_empty_n");
    sc_trace(mVcdFile, data_V_data_7_V_read, "(port)data_V_data_7_V_read");
    sc_trace(mVcdFile, data_V_data_8_V_dout, "(port)data_V_data_8_V_dout");
    sc_trace(mVcdFile, data_V_data_8_V_empty_n, "(port)data_V_data_8_V_empty_n");
    sc_trace(mVcdFile, data_V_data_8_V_read, "(port)data_V_data_8_V_read");
    sc_trace(mVcdFile, data_V_data_9_V_dout, "(port)data_V_data_9_V_dout");
    sc_trace(mVcdFile, data_V_data_9_V_empty_n, "(port)data_V_data_9_V_empty_n");
    sc_trace(mVcdFile, data_V_data_9_V_read, "(port)data_V_data_9_V_read");
    sc_trace(mVcdFile, data_V_data_10_V_dout, "(port)data_V_data_10_V_dout");
    sc_trace(mVcdFile, data_V_data_10_V_empty_n, "(port)data_V_data_10_V_empty_n");
    sc_trace(mVcdFile, data_V_data_10_V_read, "(port)data_V_data_10_V_read");
    sc_trace(mVcdFile, data_V_data_11_V_dout, "(port)data_V_data_11_V_dout");
    sc_trace(mVcdFile, data_V_data_11_V_empty_n, "(port)data_V_data_11_V_empty_n");
    sc_trace(mVcdFile, data_V_data_11_V_read, "(port)data_V_data_11_V_read");
    sc_trace(mVcdFile, data_V_data_12_V_dout, "(port)data_V_data_12_V_dout");
    sc_trace(mVcdFile, data_V_data_12_V_empty_n, "(port)data_V_data_12_V_empty_n");
    sc_trace(mVcdFile, data_V_data_12_V_read, "(port)data_V_data_12_V_read");
    sc_trace(mVcdFile, data_V_data_13_V_dout, "(port)data_V_data_13_V_dout");
    sc_trace(mVcdFile, data_V_data_13_V_empty_n, "(port)data_V_data_13_V_empty_n");
    sc_trace(mVcdFile, data_V_data_13_V_read, "(port)data_V_data_13_V_read");
    sc_trace(mVcdFile, data_V_data_14_V_dout, "(port)data_V_data_14_V_dout");
    sc_trace(mVcdFile, data_V_data_14_V_empty_n, "(port)data_V_data_14_V_empty_n");
    sc_trace(mVcdFile, data_V_data_14_V_read, "(port)data_V_data_14_V_read");
    sc_trace(mVcdFile, data_V_data_15_V_dout, "(port)data_V_data_15_V_dout");
    sc_trace(mVcdFile, data_V_data_15_V_empty_n, "(port)data_V_data_15_V_empty_n");
    sc_trace(mVcdFile, data_V_data_15_V_read, "(port)data_V_data_15_V_read");
    sc_trace(mVcdFile, res_V_data_0_V_din, "(port)res_V_data_0_V_din");
    sc_trace(mVcdFile, res_V_data_0_V_full_n, "(port)res_V_data_0_V_full_n");
    sc_trace(mVcdFile, res_V_data_0_V_write, "(port)res_V_data_0_V_write");
    sc_trace(mVcdFile, res_V_data_1_V_din, "(port)res_V_data_1_V_din");
    sc_trace(mVcdFile, res_V_data_1_V_full_n, "(port)res_V_data_1_V_full_n");
    sc_trace(mVcdFile, res_V_data_1_V_write, "(port)res_V_data_1_V_write");
    sc_trace(mVcdFile, res_V_data_2_V_din, "(port)res_V_data_2_V_din");
    sc_trace(mVcdFile, res_V_data_2_V_full_n, "(port)res_V_data_2_V_full_n");
    sc_trace(mVcdFile, res_V_data_2_V_write, "(port)res_V_data_2_V_write");
    sc_trace(mVcdFile, res_V_data_3_V_din, "(port)res_V_data_3_V_din");
    sc_trace(mVcdFile, res_V_data_3_V_full_n, "(port)res_V_data_3_V_full_n");
    sc_trace(mVcdFile, res_V_data_3_V_write, "(port)res_V_data_3_V_write");
    sc_trace(mVcdFile, res_V_data_4_V_din, "(port)res_V_data_4_V_din");
    sc_trace(mVcdFile, res_V_data_4_V_full_n, "(port)res_V_data_4_V_full_n");
    sc_trace(mVcdFile, res_V_data_4_V_write, "(port)res_V_data_4_V_write");
    sc_trace(mVcdFile, res_V_data_5_V_din, "(port)res_V_data_5_V_din");
    sc_trace(mVcdFile, res_V_data_5_V_full_n, "(port)res_V_data_5_V_full_n");
    sc_trace(mVcdFile, res_V_data_5_V_write, "(port)res_V_data_5_V_write");
    sc_trace(mVcdFile, res_V_data_6_V_din, "(port)res_V_data_6_V_din");
    sc_trace(mVcdFile, res_V_data_6_V_full_n, "(port)res_V_data_6_V_full_n");
    sc_trace(mVcdFile, res_V_data_6_V_write, "(port)res_V_data_6_V_write");
    sc_trace(mVcdFile, res_V_data_7_V_din, "(port)res_V_data_7_V_din");
    sc_trace(mVcdFile, res_V_data_7_V_full_n, "(port)res_V_data_7_V_full_n");
    sc_trace(mVcdFile, res_V_data_7_V_write, "(port)res_V_data_7_V_write");
    sc_trace(mVcdFile, res_V_data_8_V_din, "(port)res_V_data_8_V_din");
    sc_trace(mVcdFile, res_V_data_8_V_full_n, "(port)res_V_data_8_V_full_n");
    sc_trace(mVcdFile, res_V_data_8_V_write, "(port)res_V_data_8_V_write");
    sc_trace(mVcdFile, res_V_data_9_V_din, "(port)res_V_data_9_V_din");
    sc_trace(mVcdFile, res_V_data_9_V_full_n, "(port)res_V_data_9_V_full_n");
    sc_trace(mVcdFile, res_V_data_9_V_write, "(port)res_V_data_9_V_write");
    sc_trace(mVcdFile, res_V_data_10_V_din, "(port)res_V_data_10_V_din");
    sc_trace(mVcdFile, res_V_data_10_V_full_n, "(port)res_V_data_10_V_full_n");
    sc_trace(mVcdFile, res_V_data_10_V_write, "(port)res_V_data_10_V_write");
    sc_trace(mVcdFile, res_V_data_11_V_din, "(port)res_V_data_11_V_din");
    sc_trace(mVcdFile, res_V_data_11_V_full_n, "(port)res_V_data_11_V_full_n");
    sc_trace(mVcdFile, res_V_data_11_V_write, "(port)res_V_data_11_V_write");
    sc_trace(mVcdFile, res_V_data_12_V_din, "(port)res_V_data_12_V_din");
    sc_trace(mVcdFile, res_V_data_12_V_full_n, "(port)res_V_data_12_V_full_n");
    sc_trace(mVcdFile, res_V_data_12_V_write, "(port)res_V_data_12_V_write");
    sc_trace(mVcdFile, res_V_data_13_V_din, "(port)res_V_data_13_V_din");
    sc_trace(mVcdFile, res_V_data_13_V_full_n, "(port)res_V_data_13_V_full_n");
    sc_trace(mVcdFile, res_V_data_13_V_write, "(port)res_V_data_13_V_write");
    sc_trace(mVcdFile, res_V_data_14_V_din, "(port)res_V_data_14_V_din");
    sc_trace(mVcdFile, res_V_data_14_V_full_n, "(port)res_V_data_14_V_full_n");
    sc_trace(mVcdFile, res_V_data_14_V_write, "(port)res_V_data_14_V_write");
    sc_trace(mVcdFile, res_V_data_15_V_din, "(port)res_V_data_15_V_din");
    sc_trace(mVcdFile, res_V_data_15_V_full_n, "(port)res_V_data_15_V_full_n");
    sc_trace(mVcdFile, res_V_data_15_V_write, "(port)res_V_data_15_V_write");
    sc_trace(mVcdFile, start_out, "(port)start_out");
    sc_trace(mVcdFile, start_write, "(port)start_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, real_start, "real_start");
    sc_trace(mVcdFile, start_once_reg, "start_once_reg");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, internal_ap_ready, "internal_ap_ready");
    sc_trace(mVcdFile, io_acc_block_signal_op4, "io_acc_block_signal_op4");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1, "ap_block_state2_pp0_stage0_iter1");
    sc_trace(mVcdFile, io_acc_block_signal_op88, "io_acc_block_signal_op88");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2, "ap_block_state3_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, data_V_data_0_V_blk_n, "data_V_data_0_V_blk_n");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, data_V_data_1_V_blk_n, "data_V_data_1_V_blk_n");
    sc_trace(mVcdFile, data_V_data_2_V_blk_n, "data_V_data_2_V_blk_n");
    sc_trace(mVcdFile, data_V_data_3_V_blk_n, "data_V_data_3_V_blk_n");
    sc_trace(mVcdFile, data_V_data_4_V_blk_n, "data_V_data_4_V_blk_n");
    sc_trace(mVcdFile, data_V_data_5_V_blk_n, "data_V_data_5_V_blk_n");
    sc_trace(mVcdFile, data_V_data_6_V_blk_n, "data_V_data_6_V_blk_n");
    sc_trace(mVcdFile, data_V_data_7_V_blk_n, "data_V_data_7_V_blk_n");
    sc_trace(mVcdFile, data_V_data_8_V_blk_n, "data_V_data_8_V_blk_n");
    sc_trace(mVcdFile, data_V_data_9_V_blk_n, "data_V_data_9_V_blk_n");
    sc_trace(mVcdFile, data_V_data_10_V_blk_n, "data_V_data_10_V_blk_n");
    sc_trace(mVcdFile, data_V_data_11_V_blk_n, "data_V_data_11_V_blk_n");
    sc_trace(mVcdFile, data_V_data_12_V_blk_n, "data_V_data_12_V_blk_n");
    sc_trace(mVcdFile, data_V_data_13_V_blk_n, "data_V_data_13_V_blk_n");
    sc_trace(mVcdFile, data_V_data_14_V_blk_n, "data_V_data_14_V_blk_n");
    sc_trace(mVcdFile, data_V_data_15_V_blk_n, "data_V_data_15_V_blk_n");
    sc_trace(mVcdFile, res_V_data_0_V_blk_n, "res_V_data_0_V_blk_n");
    sc_trace(mVcdFile, res_V_data_1_V_blk_n, "res_V_data_1_V_blk_n");
    sc_trace(mVcdFile, res_V_data_2_V_blk_n, "res_V_data_2_V_blk_n");
    sc_trace(mVcdFile, res_V_data_3_V_blk_n, "res_V_data_3_V_blk_n");
    sc_trace(mVcdFile, res_V_data_4_V_blk_n, "res_V_data_4_V_blk_n");
    sc_trace(mVcdFile, res_V_data_5_V_blk_n, "res_V_data_5_V_blk_n");
    sc_trace(mVcdFile, res_V_data_6_V_blk_n, "res_V_data_6_V_blk_n");
    sc_trace(mVcdFile, res_V_data_7_V_blk_n, "res_V_data_7_V_blk_n");
    sc_trace(mVcdFile, res_V_data_8_V_blk_n, "res_V_data_8_V_blk_n");
    sc_trace(mVcdFile, res_V_data_9_V_blk_n, "res_V_data_9_V_blk_n");
    sc_trace(mVcdFile, res_V_data_10_V_blk_n, "res_V_data_10_V_blk_n");
    sc_trace(mVcdFile, res_V_data_11_V_blk_n, "res_V_data_11_V_blk_n");
    sc_trace(mVcdFile, res_V_data_12_V_blk_n, "res_V_data_12_V_blk_n");
    sc_trace(mVcdFile, res_V_data_13_V_blk_n, "res_V_data_13_V_blk_n");
    sc_trace(mVcdFile, res_V_data_14_V_blk_n, "res_V_data_14_V_blk_n");
    sc_trace(mVcdFile, res_V_data_15_V_blk_n, "res_V_data_15_V_blk_n");
    sc_trace(mVcdFile, tmp_data_V_0_reg_442, "tmp_data_V_0_reg_442");
    sc_trace(mVcdFile, tmp_data_V_1_reg_448, "tmp_data_V_1_reg_448");
    sc_trace(mVcdFile, tmp_data_V_2_reg_454, "tmp_data_V_2_reg_454");
    sc_trace(mVcdFile, tmp_data_V_3_reg_460, "tmp_data_V_3_reg_460");
    sc_trace(mVcdFile, tmp_data_V_4_reg_466, "tmp_data_V_4_reg_466");
    sc_trace(mVcdFile, tmp_data_V_5_reg_472, "tmp_data_V_5_reg_472");
    sc_trace(mVcdFile, tmp_data_V_624_reg_478, "tmp_data_V_624_reg_478");
    sc_trace(mVcdFile, tmp_data_V_7_reg_484, "tmp_data_V_7_reg_484");
    sc_trace(mVcdFile, tmp_data_V_8_reg_490, "tmp_data_V_8_reg_490");
    sc_trace(mVcdFile, tmp_data_V_9_reg_496, "tmp_data_V_9_reg_496");
    sc_trace(mVcdFile, tmp_data_V_10_reg_502, "tmp_data_V_10_reg_502");
    sc_trace(mVcdFile, tmp_data_V_11_reg_508, "tmp_data_V_11_reg_508");
    sc_trace(mVcdFile, tmp_data_V_12_reg_514, "tmp_data_V_12_reg_514");
    sc_trace(mVcdFile, tmp_data_V_13_reg_520, "tmp_data_V_13_reg_520");
    sc_trace(mVcdFile, tmp_data_V_14_reg_526, "tmp_data_V_14_reg_526");
    sc_trace(mVcdFile, tmp_data_V_15_reg_532, "tmp_data_V_15_reg_532");
    sc_trace(mVcdFile, tmp_data_0_V_fu_330_p3, "tmp_data_0_V_fu_330_p3");
    sc_trace(mVcdFile, tmp_data_0_V_reg_538, "tmp_data_0_V_reg_538");
    sc_trace(mVcdFile, tmp_data_1_V_fu_337_p3, "tmp_data_1_V_fu_337_p3");
    sc_trace(mVcdFile, tmp_data_1_V_reg_543, "tmp_data_1_V_reg_543");
    sc_trace(mVcdFile, tmp_data_2_V_fu_344_p3, "tmp_data_2_V_fu_344_p3");
    sc_trace(mVcdFile, tmp_data_2_V_reg_548, "tmp_data_2_V_reg_548");
    sc_trace(mVcdFile, tmp_data_3_V_fu_351_p3, "tmp_data_3_V_fu_351_p3");
    sc_trace(mVcdFile, tmp_data_3_V_reg_553, "tmp_data_3_V_reg_553");
    sc_trace(mVcdFile, tmp_data_4_V_fu_358_p3, "tmp_data_4_V_fu_358_p3");
    sc_trace(mVcdFile, tmp_data_4_V_reg_558, "tmp_data_4_V_reg_558");
    sc_trace(mVcdFile, tmp_data_5_V_fu_365_p3, "tmp_data_5_V_fu_365_p3");
    sc_trace(mVcdFile, tmp_data_5_V_reg_563, "tmp_data_5_V_reg_563");
    sc_trace(mVcdFile, tmp_data_6_V_fu_372_p3, "tmp_data_6_V_fu_372_p3");
    sc_trace(mVcdFile, tmp_data_6_V_reg_568, "tmp_data_6_V_reg_568");
    sc_trace(mVcdFile, tmp_data_7_V_fu_379_p3, "tmp_data_7_V_fu_379_p3");
    sc_trace(mVcdFile, tmp_data_7_V_reg_573, "tmp_data_7_V_reg_573");
    sc_trace(mVcdFile, tmp_data_8_V_fu_386_p3, "tmp_data_8_V_fu_386_p3");
    sc_trace(mVcdFile, tmp_data_8_V_reg_578, "tmp_data_8_V_reg_578");
    sc_trace(mVcdFile, tmp_data_9_V_fu_393_p3, "tmp_data_9_V_fu_393_p3");
    sc_trace(mVcdFile, tmp_data_9_V_reg_583, "tmp_data_9_V_reg_583");
    sc_trace(mVcdFile, tmp_data_10_V_fu_400_p3, "tmp_data_10_V_fu_400_p3");
    sc_trace(mVcdFile, tmp_data_10_V_reg_588, "tmp_data_10_V_reg_588");
    sc_trace(mVcdFile, tmp_data_11_V_fu_407_p3, "tmp_data_11_V_fu_407_p3");
    sc_trace(mVcdFile, tmp_data_11_V_reg_593, "tmp_data_11_V_reg_593");
    sc_trace(mVcdFile, tmp_data_12_V_fu_414_p3, "tmp_data_12_V_fu_414_p3");
    sc_trace(mVcdFile, tmp_data_12_V_reg_598, "tmp_data_12_V_reg_598");
    sc_trace(mVcdFile, tmp_data_13_V_fu_421_p3, "tmp_data_13_V_fu_421_p3");
    sc_trace(mVcdFile, tmp_data_13_V_reg_603, "tmp_data_13_V_reg_603");
    sc_trace(mVcdFile, tmp_data_14_V_fu_428_p3, "tmp_data_14_V_fu_428_p3");
    sc_trace(mVcdFile, tmp_data_14_V_reg_608, "tmp_data_14_V_reg_608");
    sc_trace(mVcdFile, tmp_data_15_V_fu_435_p3, "tmp_data_15_V_fu_435_p3");
    sc_trace(mVcdFile, tmp_data_15_V_reg_613, "tmp_data_15_V_reg_613");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, icmp_ln1494_fu_250_p2, "icmp_ln1494_fu_250_p2");
    sc_trace(mVcdFile, icmp_ln1494_1_fu_255_p2, "icmp_ln1494_1_fu_255_p2");
    sc_trace(mVcdFile, icmp_ln1494_2_fu_260_p2, "icmp_ln1494_2_fu_260_p2");
    sc_trace(mVcdFile, icmp_ln1494_3_fu_265_p2, "icmp_ln1494_3_fu_265_p2");
    sc_trace(mVcdFile, icmp_ln1494_4_fu_270_p2, "icmp_ln1494_4_fu_270_p2");
    sc_trace(mVcdFile, icmp_ln1494_5_fu_275_p2, "icmp_ln1494_5_fu_275_p2");
    sc_trace(mVcdFile, icmp_ln1494_6_fu_280_p2, "icmp_ln1494_6_fu_280_p2");
    sc_trace(mVcdFile, icmp_ln1494_7_fu_285_p2, "icmp_ln1494_7_fu_285_p2");
    sc_trace(mVcdFile, icmp_ln1494_8_fu_290_p2, "icmp_ln1494_8_fu_290_p2");
    sc_trace(mVcdFile, icmp_ln1494_9_fu_295_p2, "icmp_ln1494_9_fu_295_p2");
    sc_trace(mVcdFile, icmp_ln1494_10_fu_300_p2, "icmp_ln1494_10_fu_300_p2");
    sc_trace(mVcdFile, icmp_ln1494_11_fu_305_p2, "icmp_ln1494_11_fu_305_p2");
    sc_trace(mVcdFile, icmp_ln1494_12_fu_310_p2, "icmp_ln1494_12_fu_310_p2");
    sc_trace(mVcdFile, icmp_ln1494_13_fu_315_p2, "icmp_ln1494_13_fu_315_p2");
    sc_trace(mVcdFile, icmp_ln1494_14_fu_320_p2, "icmp_ln1494_14_fu_320_p2");
    sc_trace(mVcdFile, icmp_ln1494_15_fu_325_p2, "icmp_ln1494_15_fu_325_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0_0to1, "ap_idle_pp0_0to1");
    sc_trace(mVcdFile, ap_reset_idle_pp0, "ap_reset_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::~relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_pp0_stage0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter1 = real_start.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        start_once_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_0, internal_ap_ready.read()))) {
            start_once_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, internal_ap_ready.read())) {
            start_once_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        tmp_data_0_V_reg_538 = tmp_data_0_V_fu_330_p3.read();
        tmp_data_10_V_reg_588 = tmp_data_10_V_fu_400_p3.read();
        tmp_data_11_V_reg_593 = tmp_data_11_V_fu_407_p3.read();
        tmp_data_12_V_reg_598 = tmp_data_12_V_fu_414_p3.read();
        tmp_data_13_V_reg_603 = tmp_data_13_V_fu_421_p3.read();
        tmp_data_14_V_reg_608 = tmp_data_14_V_fu_428_p3.read();
        tmp_data_15_V_reg_613 = tmp_data_15_V_fu_435_p3.read();
        tmp_data_1_V_reg_543 = tmp_data_1_V_fu_337_p3.read();
        tmp_data_2_V_reg_548 = tmp_data_2_V_fu_344_p3.read();
        tmp_data_3_V_reg_553 = tmp_data_3_V_fu_351_p3.read();
        tmp_data_4_V_reg_558 = tmp_data_4_V_fu_358_p3.read();
        tmp_data_5_V_reg_563 = tmp_data_5_V_fu_365_p3.read();
        tmp_data_6_V_reg_568 = tmp_data_6_V_fu_372_p3.read();
        tmp_data_7_V_reg_573 = tmp_data_7_V_fu_379_p3.read();
        tmp_data_8_V_reg_578 = tmp_data_8_V_fu_386_p3.read();
        tmp_data_9_V_reg_583 = tmp_data_9_V_fu_393_p3.read();
        tmp_data_V_0_reg_442 = data_V_data_0_V_dout.read();
        tmp_data_V_10_reg_502 = data_V_data_10_V_dout.read();
        tmp_data_V_11_reg_508 = data_V_data_11_V_dout.read();
        tmp_data_V_12_reg_514 = data_V_data_12_V_dout.read();
        tmp_data_V_13_reg_520 = data_V_data_13_V_dout.read();
        tmp_data_V_14_reg_526 = data_V_data_14_V_dout.read();
        tmp_data_V_15_reg_532 = data_V_data_15_V_dout.read();
        tmp_data_V_1_reg_448 = data_V_data_1_V_dout.read();
        tmp_data_V_2_reg_454 = data_V_data_2_V_dout.read();
        tmp_data_V_3_reg_460 = data_V_data_3_V_dout.read();
        tmp_data_V_4_reg_466 = data_V_data_4_V_dout.read();
        tmp_data_V_5_reg_472 = data_V_data_5_V_dout.read();
        tmp_data_V_624_reg_478 = data_V_data_6_V_dout.read();
        tmp_data_V_7_reg_484 = data_V_data_7_V_dout.read();
        tmp_data_V_8_reg_490 = data_V_data_8_V_dout.read();
        tmp_data_V_9_reg_496 = data_V_data_9_V_dout.read();
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[0];
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = (esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op4.read()) || 
   esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1))) || (esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op88.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read())));
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op4.read()) || 
   esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1))) || (esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op88.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read())));
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = (esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op4.read()) || 
   esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1))) || (esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op88.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read())));
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = (esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op4.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_ap_block_state2_pp0_stage0_iter1() {
    ap_block_state2_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_ap_block_state3_pp0_stage0_iter2() {
    ap_block_state3_pp0_stage0_iter2 = esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op88.read());
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_ap_enable_reg_pp0_iter0() {
    ap_enable_reg_pp0_iter0 = real_start.read();
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_ap_idle_pp0_0to1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0_0to1 = ap_const_logic_1;
    } else {
        ap_idle_pp0_0to1 = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_ap_ready() {
    ap_ready = internal_ap_ready.read();
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_ap_reset_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0_0to1.read()))) {
        ap_reset_idle_pp0 = ap_const_logic_1;
    } else {
        ap_reset_idle_pp0 = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_data_V_data_0_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        data_V_data_0_V_blk_n = data_V_data_0_V_empty_n.read();
    } else {
        data_V_data_0_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_data_V_data_0_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_V_data_0_V_read = ap_const_logic_1;
    } else {
        data_V_data_0_V_read = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_data_V_data_10_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        data_V_data_10_V_blk_n = data_V_data_10_V_empty_n.read();
    } else {
        data_V_data_10_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_data_V_data_10_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_V_data_10_V_read = ap_const_logic_1;
    } else {
        data_V_data_10_V_read = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_data_V_data_11_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        data_V_data_11_V_blk_n = data_V_data_11_V_empty_n.read();
    } else {
        data_V_data_11_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_data_V_data_11_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_V_data_11_V_read = ap_const_logic_1;
    } else {
        data_V_data_11_V_read = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_data_V_data_12_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        data_V_data_12_V_blk_n = data_V_data_12_V_empty_n.read();
    } else {
        data_V_data_12_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_data_V_data_12_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_V_data_12_V_read = ap_const_logic_1;
    } else {
        data_V_data_12_V_read = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_data_V_data_13_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        data_V_data_13_V_blk_n = data_V_data_13_V_empty_n.read();
    } else {
        data_V_data_13_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_data_V_data_13_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_V_data_13_V_read = ap_const_logic_1;
    } else {
        data_V_data_13_V_read = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_data_V_data_14_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        data_V_data_14_V_blk_n = data_V_data_14_V_empty_n.read();
    } else {
        data_V_data_14_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_data_V_data_14_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_V_data_14_V_read = ap_const_logic_1;
    } else {
        data_V_data_14_V_read = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_data_V_data_15_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        data_V_data_15_V_blk_n = data_V_data_15_V_empty_n.read();
    } else {
        data_V_data_15_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_data_V_data_15_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_V_data_15_V_read = ap_const_logic_1;
    } else {
        data_V_data_15_V_read = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_data_V_data_1_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        data_V_data_1_V_blk_n = data_V_data_1_V_empty_n.read();
    } else {
        data_V_data_1_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_data_V_data_1_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_V_data_1_V_read = ap_const_logic_1;
    } else {
        data_V_data_1_V_read = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_data_V_data_2_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        data_V_data_2_V_blk_n = data_V_data_2_V_empty_n.read();
    } else {
        data_V_data_2_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_data_V_data_2_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_V_data_2_V_read = ap_const_logic_1;
    } else {
        data_V_data_2_V_read = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_data_V_data_3_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        data_V_data_3_V_blk_n = data_V_data_3_V_empty_n.read();
    } else {
        data_V_data_3_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_data_V_data_3_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_V_data_3_V_read = ap_const_logic_1;
    } else {
        data_V_data_3_V_read = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_data_V_data_4_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        data_V_data_4_V_blk_n = data_V_data_4_V_empty_n.read();
    } else {
        data_V_data_4_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_data_V_data_4_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_V_data_4_V_read = ap_const_logic_1;
    } else {
        data_V_data_4_V_read = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_data_V_data_5_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        data_V_data_5_V_blk_n = data_V_data_5_V_empty_n.read();
    } else {
        data_V_data_5_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_data_V_data_5_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_V_data_5_V_read = ap_const_logic_1;
    } else {
        data_V_data_5_V_read = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_data_V_data_6_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        data_V_data_6_V_blk_n = data_V_data_6_V_empty_n.read();
    } else {
        data_V_data_6_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_data_V_data_6_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_V_data_6_V_read = ap_const_logic_1;
    } else {
        data_V_data_6_V_read = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_data_V_data_7_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        data_V_data_7_V_blk_n = data_V_data_7_V_empty_n.read();
    } else {
        data_V_data_7_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_data_V_data_7_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_V_data_7_V_read = ap_const_logic_1;
    } else {
        data_V_data_7_V_read = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_data_V_data_8_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        data_V_data_8_V_blk_n = data_V_data_8_V_empty_n.read();
    } else {
        data_V_data_8_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_data_V_data_8_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_V_data_8_V_read = ap_const_logic_1;
    } else {
        data_V_data_8_V_read = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_data_V_data_9_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        data_V_data_9_V_blk_n = data_V_data_9_V_empty_n.read();
    } else {
        data_V_data_9_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_data_V_data_9_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_V_data_9_V_read = ap_const_logic_1;
    } else {
        data_V_data_9_V_read = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_icmp_ln1494_10_fu_300_p2() {
    icmp_ln1494_10_fu_300_p2 = (!tmp_data_V_10_reg_502.read().is_01() || !ap_const_lv20_0.is_01())? sc_lv<1>(): (sc_bigint<20>(tmp_data_V_10_reg_502.read()) > sc_bigint<20>(ap_const_lv20_0));
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_icmp_ln1494_11_fu_305_p2() {
    icmp_ln1494_11_fu_305_p2 = (!tmp_data_V_11_reg_508.read().is_01() || !ap_const_lv20_0.is_01())? sc_lv<1>(): (sc_bigint<20>(tmp_data_V_11_reg_508.read()) > sc_bigint<20>(ap_const_lv20_0));
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_icmp_ln1494_12_fu_310_p2() {
    icmp_ln1494_12_fu_310_p2 = (!tmp_data_V_12_reg_514.read().is_01() || !ap_const_lv20_0.is_01())? sc_lv<1>(): (sc_bigint<20>(tmp_data_V_12_reg_514.read()) > sc_bigint<20>(ap_const_lv20_0));
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_icmp_ln1494_13_fu_315_p2() {
    icmp_ln1494_13_fu_315_p2 = (!tmp_data_V_13_reg_520.read().is_01() || !ap_const_lv20_0.is_01())? sc_lv<1>(): (sc_bigint<20>(tmp_data_V_13_reg_520.read()) > sc_bigint<20>(ap_const_lv20_0));
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_icmp_ln1494_14_fu_320_p2() {
    icmp_ln1494_14_fu_320_p2 = (!tmp_data_V_14_reg_526.read().is_01() || !ap_const_lv20_0.is_01())? sc_lv<1>(): (sc_bigint<20>(tmp_data_V_14_reg_526.read()) > sc_bigint<20>(ap_const_lv20_0));
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_icmp_ln1494_15_fu_325_p2() {
    icmp_ln1494_15_fu_325_p2 = (!tmp_data_V_15_reg_532.read().is_01() || !ap_const_lv20_0.is_01())? sc_lv<1>(): (sc_bigint<20>(tmp_data_V_15_reg_532.read()) > sc_bigint<20>(ap_const_lv20_0));
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_icmp_ln1494_1_fu_255_p2() {
    icmp_ln1494_1_fu_255_p2 = (!tmp_data_V_1_reg_448.read().is_01() || !ap_const_lv20_0.is_01())? sc_lv<1>(): (sc_bigint<20>(tmp_data_V_1_reg_448.read()) > sc_bigint<20>(ap_const_lv20_0));
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_icmp_ln1494_2_fu_260_p2() {
    icmp_ln1494_2_fu_260_p2 = (!tmp_data_V_2_reg_454.read().is_01() || !ap_const_lv20_0.is_01())? sc_lv<1>(): (sc_bigint<20>(tmp_data_V_2_reg_454.read()) > sc_bigint<20>(ap_const_lv20_0));
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_icmp_ln1494_3_fu_265_p2() {
    icmp_ln1494_3_fu_265_p2 = (!tmp_data_V_3_reg_460.read().is_01() || !ap_const_lv20_0.is_01())? sc_lv<1>(): (sc_bigint<20>(tmp_data_V_3_reg_460.read()) > sc_bigint<20>(ap_const_lv20_0));
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_icmp_ln1494_4_fu_270_p2() {
    icmp_ln1494_4_fu_270_p2 = (!tmp_data_V_4_reg_466.read().is_01() || !ap_const_lv20_0.is_01())? sc_lv<1>(): (sc_bigint<20>(tmp_data_V_4_reg_466.read()) > sc_bigint<20>(ap_const_lv20_0));
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_icmp_ln1494_5_fu_275_p2() {
    icmp_ln1494_5_fu_275_p2 = (!tmp_data_V_5_reg_472.read().is_01() || !ap_const_lv20_0.is_01())? sc_lv<1>(): (sc_bigint<20>(tmp_data_V_5_reg_472.read()) > sc_bigint<20>(ap_const_lv20_0));
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_icmp_ln1494_6_fu_280_p2() {
    icmp_ln1494_6_fu_280_p2 = (!tmp_data_V_624_reg_478.read().is_01() || !ap_const_lv20_0.is_01())? sc_lv<1>(): (sc_bigint<20>(tmp_data_V_624_reg_478.read()) > sc_bigint<20>(ap_const_lv20_0));
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_icmp_ln1494_7_fu_285_p2() {
    icmp_ln1494_7_fu_285_p2 = (!tmp_data_V_7_reg_484.read().is_01() || !ap_const_lv20_0.is_01())? sc_lv<1>(): (sc_bigint<20>(tmp_data_V_7_reg_484.read()) > sc_bigint<20>(ap_const_lv20_0));
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_icmp_ln1494_8_fu_290_p2() {
    icmp_ln1494_8_fu_290_p2 = (!tmp_data_V_8_reg_490.read().is_01() || !ap_const_lv20_0.is_01())? sc_lv<1>(): (sc_bigint<20>(tmp_data_V_8_reg_490.read()) > sc_bigint<20>(ap_const_lv20_0));
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_icmp_ln1494_9_fu_295_p2() {
    icmp_ln1494_9_fu_295_p2 = (!tmp_data_V_9_reg_496.read().is_01() || !ap_const_lv20_0.is_01())? sc_lv<1>(): (sc_bigint<20>(tmp_data_V_9_reg_496.read()) > sc_bigint<20>(ap_const_lv20_0));
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_icmp_ln1494_fu_250_p2() {
    icmp_ln1494_fu_250_p2 = (!tmp_data_V_0_reg_442.read().is_01() || !ap_const_lv20_0.is_01())? sc_lv<1>(): (sc_bigint<20>(tmp_data_V_0_reg_442.read()) > sc_bigint<20>(ap_const_lv20_0));
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_internal_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        internal_ap_ready = ap_const_logic_1;
    } else {
        internal_ap_ready = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_io_acc_block_signal_op4() {
    io_acc_block_signal_op4 = (data_V_data_0_V_empty_n.read() & data_V_data_1_V_empty_n.read() & data_V_data_2_V_empty_n.read() & data_V_data_3_V_empty_n.read() & data_V_data_4_V_empty_n.read() & data_V_data_5_V_empty_n.read() & data_V_data_6_V_empty_n.read() & data_V_data_7_V_empty_n.read() & data_V_data_8_V_empty_n.read() & data_V_data_9_V_empty_n.read() & data_V_data_10_V_empty_n.read() & data_V_data_11_V_empty_n.read() & data_V_data_12_V_empty_n.read() & data_V_data_13_V_empty_n.read() & data_V_data_14_V_empty_n.read() & data_V_data_15_V_empty_n.read());
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_io_acc_block_signal_op88() {
    io_acc_block_signal_op88 = (res_V_data_0_V_full_n.read() & res_V_data_1_V_full_n.read() & res_V_data_2_V_full_n.read() & res_V_data_3_V_full_n.read() & res_V_data_4_V_full_n.read() & res_V_data_5_V_full_n.read() & res_V_data_6_V_full_n.read() & res_V_data_7_V_full_n.read() & res_V_data_8_V_full_n.read() & res_V_data_9_V_full_n.read() & res_V_data_10_V_full_n.read() & res_V_data_11_V_full_n.read() & res_V_data_12_V_full_n.read() & res_V_data_13_V_full_n.read() & res_V_data_14_V_full_n.read() & res_V_data_15_V_full_n.read());
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_real_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_full_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()))) {
        real_start = ap_const_logic_0;
    } else {
        real_start = ap_start.read();
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_0_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        res_V_data_0_V_blk_n = res_V_data_0_V_full_n.read();
    } else {
        res_V_data_0_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_0_V_din() {
    res_V_data_0_V_din = tmp_data_0_V_reg_538.read();
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_0_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        res_V_data_0_V_write = ap_const_logic_1;
    } else {
        res_V_data_0_V_write = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_10_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        res_V_data_10_V_blk_n = res_V_data_10_V_full_n.read();
    } else {
        res_V_data_10_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_10_V_din() {
    res_V_data_10_V_din = tmp_data_10_V_reg_588.read();
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_10_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        res_V_data_10_V_write = ap_const_logic_1;
    } else {
        res_V_data_10_V_write = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_11_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        res_V_data_11_V_blk_n = res_V_data_11_V_full_n.read();
    } else {
        res_V_data_11_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_11_V_din() {
    res_V_data_11_V_din = tmp_data_11_V_reg_593.read();
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_11_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        res_V_data_11_V_write = ap_const_logic_1;
    } else {
        res_V_data_11_V_write = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_12_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        res_V_data_12_V_blk_n = res_V_data_12_V_full_n.read();
    } else {
        res_V_data_12_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_12_V_din() {
    res_V_data_12_V_din = tmp_data_12_V_reg_598.read();
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_12_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        res_V_data_12_V_write = ap_const_logic_1;
    } else {
        res_V_data_12_V_write = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_13_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        res_V_data_13_V_blk_n = res_V_data_13_V_full_n.read();
    } else {
        res_V_data_13_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_13_V_din() {
    res_V_data_13_V_din = tmp_data_13_V_reg_603.read();
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_13_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        res_V_data_13_V_write = ap_const_logic_1;
    } else {
        res_V_data_13_V_write = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_14_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        res_V_data_14_V_blk_n = res_V_data_14_V_full_n.read();
    } else {
        res_V_data_14_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_14_V_din() {
    res_V_data_14_V_din = tmp_data_14_V_reg_608.read();
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_14_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        res_V_data_14_V_write = ap_const_logic_1;
    } else {
        res_V_data_14_V_write = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_15_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        res_V_data_15_V_blk_n = res_V_data_15_V_full_n.read();
    } else {
        res_V_data_15_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_15_V_din() {
    res_V_data_15_V_din = tmp_data_15_V_reg_613.read();
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_15_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        res_V_data_15_V_write = ap_const_logic_1;
    } else {
        res_V_data_15_V_write = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_1_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        res_V_data_1_V_blk_n = res_V_data_1_V_full_n.read();
    } else {
        res_V_data_1_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_1_V_din() {
    res_V_data_1_V_din = tmp_data_1_V_reg_543.read();
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_1_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        res_V_data_1_V_write = ap_const_logic_1;
    } else {
        res_V_data_1_V_write = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_2_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        res_V_data_2_V_blk_n = res_V_data_2_V_full_n.read();
    } else {
        res_V_data_2_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_2_V_din() {
    res_V_data_2_V_din = tmp_data_2_V_reg_548.read();
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_2_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        res_V_data_2_V_write = ap_const_logic_1;
    } else {
        res_V_data_2_V_write = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_3_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        res_V_data_3_V_blk_n = res_V_data_3_V_full_n.read();
    } else {
        res_V_data_3_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_3_V_din() {
    res_V_data_3_V_din = tmp_data_3_V_reg_553.read();
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_3_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        res_V_data_3_V_write = ap_const_logic_1;
    } else {
        res_V_data_3_V_write = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_4_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        res_V_data_4_V_blk_n = res_V_data_4_V_full_n.read();
    } else {
        res_V_data_4_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_4_V_din() {
    res_V_data_4_V_din = tmp_data_4_V_reg_558.read();
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_4_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        res_V_data_4_V_write = ap_const_logic_1;
    } else {
        res_V_data_4_V_write = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_5_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        res_V_data_5_V_blk_n = res_V_data_5_V_full_n.read();
    } else {
        res_V_data_5_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_5_V_din() {
    res_V_data_5_V_din = tmp_data_5_V_reg_563.read();
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_5_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        res_V_data_5_V_write = ap_const_logic_1;
    } else {
        res_V_data_5_V_write = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_6_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        res_V_data_6_V_blk_n = res_V_data_6_V_full_n.read();
    } else {
        res_V_data_6_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_6_V_din() {
    res_V_data_6_V_din = tmp_data_6_V_reg_568.read();
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_6_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        res_V_data_6_V_write = ap_const_logic_1;
    } else {
        res_V_data_6_V_write = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_7_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        res_V_data_7_V_blk_n = res_V_data_7_V_full_n.read();
    } else {
        res_V_data_7_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_7_V_din() {
    res_V_data_7_V_din = tmp_data_7_V_reg_573.read();
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_7_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        res_V_data_7_V_write = ap_const_logic_1;
    } else {
        res_V_data_7_V_write = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_8_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        res_V_data_8_V_blk_n = res_V_data_8_V_full_n.read();
    } else {
        res_V_data_8_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_8_V_din() {
    res_V_data_8_V_din = tmp_data_8_V_reg_578.read();
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_8_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        res_V_data_8_V_write = ap_const_logic_1;
    } else {
        res_V_data_8_V_write = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_9_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        res_V_data_9_V_blk_n = res_V_data_9_V_full_n.read();
    } else {
        res_V_data_9_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_9_V_din() {
    res_V_data_9_V_din = tmp_data_9_V_reg_583.read();
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_res_V_data_9_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        res_V_data_9_V_write = ap_const_logic_1;
    } else {
        res_V_data_9_V_write = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_start_out() {
    start_out = real_start.read();
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_start_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()))) {
        start_write = ap_const_logic_1;
    } else {
        start_write = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_tmp_data_0_V_fu_330_p3() {
    tmp_data_0_V_fu_330_p3 = (!icmp_ln1494_fu_250_p2.read()[0].is_01())? sc_lv<20>(): ((icmp_ln1494_fu_250_p2.read()[0].to_bool())? tmp_data_V_0_reg_442.read(): ap_const_lv20_0);
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_tmp_data_10_V_fu_400_p3() {
    tmp_data_10_V_fu_400_p3 = (!icmp_ln1494_10_fu_300_p2.read()[0].is_01())? sc_lv<20>(): ((icmp_ln1494_10_fu_300_p2.read()[0].to_bool())? tmp_data_V_10_reg_502.read(): ap_const_lv20_0);
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_tmp_data_11_V_fu_407_p3() {
    tmp_data_11_V_fu_407_p3 = (!icmp_ln1494_11_fu_305_p2.read()[0].is_01())? sc_lv<20>(): ((icmp_ln1494_11_fu_305_p2.read()[0].to_bool())? tmp_data_V_11_reg_508.read(): ap_const_lv20_0);
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_tmp_data_12_V_fu_414_p3() {
    tmp_data_12_V_fu_414_p3 = (!icmp_ln1494_12_fu_310_p2.read()[0].is_01())? sc_lv<20>(): ((icmp_ln1494_12_fu_310_p2.read()[0].to_bool())? tmp_data_V_12_reg_514.read(): ap_const_lv20_0);
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_tmp_data_13_V_fu_421_p3() {
    tmp_data_13_V_fu_421_p3 = (!icmp_ln1494_13_fu_315_p2.read()[0].is_01())? sc_lv<20>(): ((icmp_ln1494_13_fu_315_p2.read()[0].to_bool())? tmp_data_V_13_reg_520.read(): ap_const_lv20_0);
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_tmp_data_14_V_fu_428_p3() {
    tmp_data_14_V_fu_428_p3 = (!icmp_ln1494_14_fu_320_p2.read()[0].is_01())? sc_lv<20>(): ((icmp_ln1494_14_fu_320_p2.read()[0].to_bool())? tmp_data_V_14_reg_526.read(): ap_const_lv20_0);
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_tmp_data_15_V_fu_435_p3() {
    tmp_data_15_V_fu_435_p3 = (!icmp_ln1494_15_fu_325_p2.read()[0].is_01())? sc_lv<20>(): ((icmp_ln1494_15_fu_325_p2.read()[0].to_bool())? tmp_data_V_15_reg_532.read(): ap_const_lv20_0);
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_tmp_data_1_V_fu_337_p3() {
    tmp_data_1_V_fu_337_p3 = (!icmp_ln1494_1_fu_255_p2.read()[0].is_01())? sc_lv<20>(): ((icmp_ln1494_1_fu_255_p2.read()[0].to_bool())? tmp_data_V_1_reg_448.read(): ap_const_lv20_0);
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_tmp_data_2_V_fu_344_p3() {
    tmp_data_2_V_fu_344_p3 = (!icmp_ln1494_2_fu_260_p2.read()[0].is_01())? sc_lv<20>(): ((icmp_ln1494_2_fu_260_p2.read()[0].to_bool())? tmp_data_V_2_reg_454.read(): ap_const_lv20_0);
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_tmp_data_3_V_fu_351_p3() {
    tmp_data_3_V_fu_351_p3 = (!icmp_ln1494_3_fu_265_p2.read()[0].is_01())? sc_lv<20>(): ((icmp_ln1494_3_fu_265_p2.read()[0].to_bool())? tmp_data_V_3_reg_460.read(): ap_const_lv20_0);
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_tmp_data_4_V_fu_358_p3() {
    tmp_data_4_V_fu_358_p3 = (!icmp_ln1494_4_fu_270_p2.read()[0].is_01())? sc_lv<20>(): ((icmp_ln1494_4_fu_270_p2.read()[0].to_bool())? tmp_data_V_4_reg_466.read(): ap_const_lv20_0);
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_tmp_data_5_V_fu_365_p3() {
    tmp_data_5_V_fu_365_p3 = (!icmp_ln1494_5_fu_275_p2.read()[0].is_01())? sc_lv<20>(): ((icmp_ln1494_5_fu_275_p2.read()[0].to_bool())? tmp_data_V_5_reg_472.read(): ap_const_lv20_0);
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_tmp_data_6_V_fu_372_p3() {
    tmp_data_6_V_fu_372_p3 = (!icmp_ln1494_6_fu_280_p2.read()[0].is_01())? sc_lv<20>(): ((icmp_ln1494_6_fu_280_p2.read()[0].to_bool())? tmp_data_V_624_reg_478.read(): ap_const_lv20_0);
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_tmp_data_7_V_fu_379_p3() {
    tmp_data_7_V_fu_379_p3 = (!icmp_ln1494_7_fu_285_p2.read()[0].is_01())? sc_lv<20>(): ((icmp_ln1494_7_fu_285_p2.read()[0].to_bool())? tmp_data_V_7_reg_484.read(): ap_const_lv20_0);
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_tmp_data_8_V_fu_386_p3() {
    tmp_data_8_V_fu_386_p3 = (!icmp_ln1494_8_fu_290_p2.read()[0].is_01())? sc_lv<20>(): ((icmp_ln1494_8_fu_290_p2.read()[0].to_bool())? tmp_data_V_8_reg_490.read(): ap_const_lv20_0);
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_tmp_data_9_V_fu_393_p3() {
    tmp_data_9_V_fu_393_p3 = (!icmp_ln1494_9_fu_295_p2.read()[0].is_01())? sc_lv<20>(): ((icmp_ln1494_9_fu_295_p2.read()[0].to_bool())? tmp_data_V_9_reg_496.read(): ap_const_lv20_0);
}

void relu_array_ap_fixed_16u_array_ap_fixed_20_8_5_3_0_16u_relu_config25_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

}

