// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::ap_ST_fsm_pp0_stage0 = "1";
const sc_lv<3> softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::ap_ST_fsm_pp0_stage1 = "10";
const sc_lv<3> softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::ap_ST_fsm_pp0_stage2 = "100";
const bool softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::ap_const_boolean_1 = true;
const sc_lv<32> softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::ap_const_boolean_0 = false;
const sc_lv<32> softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::ap_const_lv32_2 = "10";
const sc_lv<32> softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::ap_const_lv32_1 = "1";
const sc_lv<32> softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::ap_const_lv32_8 = "1000";
const sc_lv<32> softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::ap_const_lv32_1B = "11011";
const sc_lv<32> softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::ap_const_lv32_14 = "10100";
const sc_lv<32> softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::ap_const_lv32_13 = "10011";
const sc_lv<1> softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::ap_const_lv1_1 = "1";
const sc_lv<32> softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::ap_const_lv32_A = "1010";
const sc_lv<10> softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::ap_const_lv10_1FF = "111111111";
const sc_lv<10> softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::ap_const_lv10_200 = "1000000000";
const sc_lv<32> softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::ap_const_lv32_12 = "10010";
const sc_lv<32> softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::ap_const_lv32_11 = "10001";

softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    exp_table4_U = new softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s_exp_table4("exp_table4_U");
    exp_table4_U->clk(ap_clk);
    exp_table4_U->reset(ap_rst);
    exp_table4_U->address0(exp_table4_address0);
    exp_table4_U->ce0(exp_table4_ce0);
    exp_table4_U->q0(exp_table4_q0);
    invert_table5_U = new softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s_invert_tbfk("invert_table5_U");
    invert_table5_U->clk(ap_clk);
    invert_table5_U->reset(ap_rst);
    invert_table5_U->address0(invert_table5_address0);
    invert_table5_U->ce0(invert_table5_ce0);
    invert_table5_U->q0(invert_table5_q0);
    myproject_axi_mul_17ns_18s_28_2_1_U434 = new myproject_axi_mul_17ns_18s_28_2_1<1,2,17,18,28>("myproject_axi_mul_17ns_18s_28_2_1_U434");
    myproject_axi_mul_17ns_18s_28_2_1_U434->clk(ap_clk);
    myproject_axi_mul_17ns_18s_28_2_1_U434->reset(ap_rst);
    myproject_axi_mul_17ns_18s_28_2_1_U434->din0(grp_fu_153_p0);
    myproject_axi_mul_17ns_18s_28_2_1_U434->din1(grp_fu_153_p1);
    myproject_axi_mul_17ns_18s_28_2_1_U434->ce(grp_fu_153_ce);
    myproject_axi_mul_17ns_18s_28_2_1_U434->dout(grp_fu_153_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_and_ln786_1_fu_302_p2);
    sensitive << ( tmp_9_fu_280_p3 );
    sensitive << ( xor_ln786_1_fu_296_p2 );

    SC_METHOD(thread_and_ln786_2_fu_357_p2);
    sensitive << ( tmp_11_fu_335_p3 );
    sensitive << ( xor_ln786_2_fu_351_p2 );

    SC_METHOD(thread_and_ln786_fu_247_p2);
    sensitive << ( tmp_5_fu_225_p3 );
    sensitive << ( xor_ln786_fu_241_p2 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( io_acc_block_signal_op17 );
    sensitive << ( io_acc_block_signal_op131 );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( io_acc_block_signal_op17 );
    sensitive << ( io_acc_block_signal_op131 );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( io_acc_block_signal_op17 );
    sensitive << ( io_acc_block_signal_op131 );

    SC_METHOD(thread_ap_block_pp0_stage1);

    SC_METHOD(thread_ap_block_pp0_stage1_11001);

    SC_METHOD(thread_ap_block_pp0_stage1_subdone);

    SC_METHOD(thread_ap_block_pp0_stage2);

    SC_METHOD(thread_ap_block_pp0_stage2_11001);

    SC_METHOD(thread_ap_block_pp0_stage2_subdone);

    SC_METHOD(thread_ap_block_state10_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state11_pp0_stage1_iter3);

    SC_METHOD(thread_ap_block_state12_pp0_stage2_iter3);

    SC_METHOD(thread_ap_block_state13_pp0_stage0_iter4);

    SC_METHOD(thread_ap_block_state14_pp0_stage1_iter4);

    SC_METHOD(thread_ap_block_state15_pp0_stage2_iter4);

    SC_METHOD(thread_ap_block_state16_pp0_stage0_iter5);
    sensitive << ( io_acc_block_signal_op131 );

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);
    sensitive << ( ap_start );
    sensitive << ( io_acc_block_signal_op17 );

    SC_METHOD(thread_ap_block_state2_pp0_stage1_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage2_iter0);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state5_pp0_stage1_iter1);

    SC_METHOD(thread_ap_block_state6_pp0_stage2_iter1);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state8_pp0_stage1_iter2);

    SC_METHOD(thread_ap_block_state9_pp0_stage2_iter2);

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_reg_pp0_iter0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0_reg );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter5 );

    SC_METHOD(thread_ap_idle_pp0_0to4);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );

    SC_METHOD(thread_ap_idle_pp0_1to5);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter5 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_11001 );

    SC_METHOD(thread_ap_reset_idle_pp0);
    sensitive << ( ap_start );
    sensitive << ( ap_idle_pp0_0to4 );

    SC_METHOD(thread_data_V_data_0_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( data_V_data_0_V_empty_n );

    SC_METHOD(thread_data_V_data_0_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_data_V_data_1_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( data_V_data_1_V_empty_n );

    SC_METHOD(thread_data_V_data_1_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_data_V_data_2_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( data_V_data_2_V_empty_n );

    SC_METHOD(thread_data_V_data_2_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_exp_table4_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( zext_ln225_fu_483_p1 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( zext_ln225_1_fu_487_p1 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( zext_ln225_2_fu_491_p1 );

    SC_METHOD(thread_exp_table4_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_11001 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );

    SC_METHOD(thread_grp_fu_153_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_11001 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );

    SC_METHOD(thread_grp_fu_153_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( zext_ln1118_fu_615_p1 );
    sensitive << ( zext_ln1118_1_fu_619_p1 );
    sensitive << ( zext_ln1118_2_fu_623_p1 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage2 );

    SC_METHOD(thread_grp_fu_153_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( sext_ln241_fu_611_p1 );
    sensitive << ( sext_ln241_reg_728 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage2 );

    SC_METHOD(thread_icmp_ln1496_1_fu_201_p2);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_11001 );
    sensitive << ( tmp_data_2_V_1_reg_641 );
    sensitive << ( select_ln65_fu_196_p3 );

    SC_METHOD(thread_icmp_ln1496_fu_192_p2);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( tmp_data_0_V_1_reg_627 );
    sensitive << ( tmp_data_1_V_1_reg_634 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );

    SC_METHOD(thread_invert_table5_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( zext_ln235_fu_607_p1 );

    SC_METHOD(thread_invert_table5_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_io_acc_block_signal_op131);
    sensitive << ( res_V_data_0_V_full_n );
    sensitive << ( res_V_data_1_V_full_n );
    sensitive << ( res_V_data_2_V_full_n );

    SC_METHOD(thread_io_acc_block_signal_op17);
    sensitive << ( data_V_data_0_V_empty_n );
    sensitive << ( data_V_data_1_V_empty_n );
    sensitive << ( data_V_data_2_V_empty_n );

    SC_METHOD(thread_lhs_V_fu_510_p1);
    sensitive << ( ret_V_reg_707 );

    SC_METHOD(thread_or_ln340_1_fu_320_p2);
    sensitive << ( tmp_10_fu_288_p3 );
    sensitive << ( xor_ln340_1_fu_314_p2 );

    SC_METHOD(thread_or_ln340_2_fu_375_p2);
    sensitive << ( tmp_12_fu_343_p3 );
    sensitive << ( xor_ln340_2_fu_369_p2 );

    SC_METHOD(thread_or_ln340_3_fu_567_p2);
    sensitive << ( p_Result_7_fu_535_p3 );
    sensitive << ( xor_ln340_7_fu_561_p2 );

    SC_METHOD(thread_or_ln340_fu_265_p2);
    sensitive << ( tmp_7_fu_233_p3 );
    sensitive << ( xor_ln340_fu_259_p2 );

    SC_METHOD(thread_p_Result_7_fu_535_p3);
    sensitive << ( p_Val2_9_fu_530_p2 );

    SC_METHOD(thread_p_Result_s_fu_522_p3);
    sensitive << ( ret_V_1_fu_516_p2 );

    SC_METHOD(thread_p_Val2_9_fu_530_p2);
    sensitive << ( ret_V_reg_707 );
    sensitive << ( zext_ln36_fu_507_p1 );

    SC_METHOD(thread_res_V_data_0_V_blk_n);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( res_V_data_0_V_full_n );

    SC_METHOD(thread_res_V_data_0_V_din);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( tmp_data_0_V_reg_738 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_res_V_data_0_V_write);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_V_data_1_V_blk_n);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( res_V_data_1_V_full_n );

    SC_METHOD(thread_res_V_data_1_V_din);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( tmp_data_1_V_reg_748 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_res_V_data_1_V_write);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_V_data_2_V_blk_n);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( res_V_data_2_V_full_n );

    SC_METHOD(thread_res_V_data_2_V_din);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( tmp_data_2_V_reg_758 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_res_V_data_2_V_write);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_ret_V_1_fu_516_p2);
    sensitive << ( rhs_V_fu_513_p1 );
    sensitive << ( lhs_V_fu_510_p1 );

    SC_METHOD(thread_ret_V_fu_501_p2);
    sensitive << ( zext_ln36_2_fu_498_p1 );
    sensitive << ( zext_ln36_1_fu_495_p1 );

    SC_METHOD(thread_rhs_V_fu_513_p1);
    sensitive << ( exp_res_2_V_reg_700 );

    SC_METHOD(thread_select_ln340_2_fu_425_p3);
    sensitive << ( xor_ln340_4_fu_308_p2 );
    sensitive << ( tmp_6_fu_415_p4 );

    SC_METHOD(thread_select_ln340_4_fu_459_p3);
    sensitive << ( xor_ln340_5_fu_363_p2 );
    sensitive << ( tmp_8_fu_449_p4 );

    SC_METHOD(thread_select_ln340_6_fu_583_p3);
    sensitive << ( xor_ln340_6_fu_555_p2 );
    sensitive << ( tmp_s_fu_573_p4 );

    SC_METHOD(thread_select_ln340_fu_391_p3);
    sensitive << ( xor_ln340_3_fu_253_p2 );
    sensitive << ( tmp_fu_381_p4 );

    SC_METHOD(thread_select_ln388_1_fu_433_p3);
    sensitive << ( tmp_6_fu_415_p4 );
    sensitive << ( and_ln786_1_fu_302_p2 );

    SC_METHOD(thread_select_ln388_2_fu_467_p3);
    sensitive << ( tmp_8_fu_449_p4 );
    sensitive << ( and_ln786_2_fu_357_p2 );

    SC_METHOD(thread_select_ln388_3_fu_591_p3);
    sensitive << ( tmp_s_fu_573_p4 );
    sensitive << ( underflow_fu_549_p2 );

    SC_METHOD(thread_select_ln388_fu_399_p3);
    sensitive << ( tmp_fu_381_p4 );
    sensitive << ( and_ln786_fu_247_p2 );

    SC_METHOD(thread_select_ln65_fu_196_p3);
    sensitive << ( tmp_data_0_V_1_reg_627 );
    sensitive << ( tmp_data_1_V_1_reg_634 );
    sensitive << ( icmp_ln1496_reg_648 );

    SC_METHOD(thread_sext_ln241_fu_611_p1);
    sensitive << ( inv_exp_sum_V_reg_723 );

    SC_METHOD(thread_sext_ln703_1_fu_216_p1);
    sensitive << ( x_max_V_reg_653 );

    SC_METHOD(thread_sext_ln703_2_fu_271_p1);
    sensitive << ( tmp_data_1_V_1_reg_634 );

    SC_METHOD(thread_sext_ln703_3_fu_326_p1);
    sensitive << ( tmp_data_2_V_1_reg_641 );

    SC_METHOD(thread_sext_ln703_fu_213_p1);
    sensitive << ( tmp_data_0_V_1_reg_627 );

    SC_METHOD(thread_sub_ln1193_1_fu_274_p2);
    sensitive << ( sext_ln703_1_fu_216_p1 );
    sensitive << ( sext_ln703_2_fu_271_p1 );

    SC_METHOD(thread_sub_ln1193_2_fu_329_p2);
    sensitive << ( sext_ln703_1_fu_216_p1 );
    sensitive << ( sext_ln703_3_fu_326_p1 );

    SC_METHOD(thread_sub_ln1193_fu_219_p2);
    sensitive << ( sext_ln703_fu_213_p1 );
    sensitive << ( sext_ln703_1_fu_216_p1 );

    SC_METHOD(thread_tmp_10_fu_288_p3);
    sensitive << ( sub_ln1193_1_fu_274_p2 );

    SC_METHOD(thread_tmp_11_fu_335_p3);
    sensitive << ( sub_ln1193_2_fu_329_p2 );

    SC_METHOD(thread_tmp_12_fu_343_p3);
    sensitive << ( sub_ln1193_2_fu_329_p2 );

    SC_METHOD(thread_tmp_5_fu_225_p3);
    sensitive << ( sub_ln1193_fu_219_p2 );

    SC_METHOD(thread_tmp_6_fu_415_p4);
    sensitive << ( sub_ln1193_1_fu_274_p2 );

    SC_METHOD(thread_tmp_7_fu_233_p3);
    sensitive << ( sub_ln1193_fu_219_p2 );

    SC_METHOD(thread_tmp_8_fu_449_p4);
    sensitive << ( sub_ln1193_2_fu_329_p2 );

    SC_METHOD(thread_tmp_9_fu_280_p3);
    sensitive << ( sub_ln1193_1_fu_274_p2 );

    SC_METHOD(thread_tmp_fu_381_p4);
    sensitive << ( sub_ln1193_fu_219_p2 );

    SC_METHOD(thread_tmp_s_fu_573_p4);
    sensitive << ( p_Val2_9_fu_530_p2 );

    SC_METHOD(thread_underflow_fu_549_p2);
    sensitive << ( p_Result_s_fu_522_p3 );
    sensitive << ( xor_ln786_3_fu_543_p2 );

    SC_METHOD(thread_x_max_V_fu_206_p3);
    sensitive << ( tmp_data_2_V_1_reg_641 );
    sensitive << ( select_ln65_fu_196_p3 );
    sensitive << ( icmp_ln1496_1_fu_201_p2 );

    SC_METHOD(thread_xor_ln340_1_fu_314_p2);
    sensitive << ( tmp_9_fu_280_p3 );

    SC_METHOD(thread_xor_ln340_2_fu_369_p2);
    sensitive << ( tmp_11_fu_335_p3 );

    SC_METHOD(thread_xor_ln340_3_fu_253_p2);
    sensitive << ( tmp_7_fu_233_p3 );
    sensitive << ( tmp_5_fu_225_p3 );

    SC_METHOD(thread_xor_ln340_4_fu_308_p2);
    sensitive << ( tmp_10_fu_288_p3 );
    sensitive << ( tmp_9_fu_280_p3 );

    SC_METHOD(thread_xor_ln340_5_fu_363_p2);
    sensitive << ( tmp_12_fu_343_p3 );
    sensitive << ( tmp_11_fu_335_p3 );

    SC_METHOD(thread_xor_ln340_6_fu_555_p2);
    sensitive << ( p_Result_7_fu_535_p3 );
    sensitive << ( p_Result_s_fu_522_p3 );

    SC_METHOD(thread_xor_ln340_7_fu_561_p2);
    sensitive << ( p_Result_s_fu_522_p3 );

    SC_METHOD(thread_xor_ln340_fu_259_p2);
    sensitive << ( tmp_5_fu_225_p3 );

    SC_METHOD(thread_xor_ln786_1_fu_296_p2);
    sensitive << ( tmp_10_fu_288_p3 );

    SC_METHOD(thread_xor_ln786_2_fu_351_p2);
    sensitive << ( tmp_12_fu_343_p3 );

    SC_METHOD(thread_xor_ln786_3_fu_543_p2);
    sensitive << ( p_Result_7_fu_535_p3 );

    SC_METHOD(thread_xor_ln786_fu_241_p2);
    sensitive << ( tmp_7_fu_233_p3 );

    SC_METHOD(thread_y_V_1_fu_441_p3);
    sensitive << ( or_ln340_1_fu_320_p2 );
    sensitive << ( select_ln340_2_fu_425_p3 );
    sensitive << ( select_ln388_1_fu_433_p3 );

    SC_METHOD(thread_y_V_2_fu_475_p3);
    sensitive << ( or_ln340_2_fu_375_p2 );
    sensitive << ( select_ln340_4_fu_459_p3 );
    sensitive << ( select_ln388_2_fu_467_p3 );

    SC_METHOD(thread_y_V_3_fu_599_p3);
    sensitive << ( or_ln340_3_fu_567_p2 );
    sensitive << ( select_ln340_6_fu_583_p3 );
    sensitive << ( select_ln388_3_fu_591_p3 );

    SC_METHOD(thread_y_V_fu_407_p3);
    sensitive << ( or_ln340_fu_265_p2 );
    sensitive << ( select_ln340_fu_391_p3 );
    sensitive << ( select_ln388_fu_399_p3 );

    SC_METHOD(thread_zext_ln1118_1_fu_619_p1);
    sensitive << ( exp_res_1_V_reg_689_pp0_iter3_reg );

    SC_METHOD(thread_zext_ln1118_2_fu_623_p1);
    sensitive << ( exp_res_2_V_reg_700_pp0_iter3_reg );

    SC_METHOD(thread_zext_ln1118_fu_615_p1);
    sensitive << ( exp_res_0_V_reg_678_pp0_iter2_reg );

    SC_METHOD(thread_zext_ln225_1_fu_487_p1);
    sensitive << ( y_V_1_reg_663 );

    SC_METHOD(thread_zext_ln225_2_fu_491_p1);
    sensitive << ( y_V_2_reg_668 );

    SC_METHOD(thread_zext_ln225_fu_483_p1);
    sensitive << ( y_V_reg_658 );

    SC_METHOD(thread_zext_ln235_fu_607_p1);
    sensitive << ( y_V_3_reg_713 );

    SC_METHOD(thread_zext_ln36_1_fu_495_p1);
    sensitive << ( exp_res_1_V_reg_689 );

    SC_METHOD(thread_zext_ln36_2_fu_498_p1);
    sensitive << ( exp_res_0_V_reg_678 );

    SC_METHOD(thread_zext_ln36_fu_507_p1);
    sensitive << ( exp_res_2_V_reg_700 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_block_pp0_stage2_subdone );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_reset_idle_pp0 );
    sensitive << ( ap_idle_pp0_1to5 );
    sensitive << ( ap_block_pp0_stage1_subdone );

    ap_CS_fsm = "001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter5 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, data_V_data_0_V_dout, "(port)data_V_data_0_V_dout");
    sc_trace(mVcdFile, data_V_data_0_V_empty_n, "(port)data_V_data_0_V_empty_n");
    sc_trace(mVcdFile, data_V_data_0_V_read, "(port)data_V_data_0_V_read");
    sc_trace(mVcdFile, data_V_data_1_V_dout, "(port)data_V_data_1_V_dout");
    sc_trace(mVcdFile, data_V_data_1_V_empty_n, "(port)data_V_data_1_V_empty_n");
    sc_trace(mVcdFile, data_V_data_1_V_read, "(port)data_V_data_1_V_read");
    sc_trace(mVcdFile, data_V_data_2_V_dout, "(port)data_V_data_2_V_dout");
    sc_trace(mVcdFile, data_V_data_2_V_empty_n, "(port)data_V_data_2_V_empty_n");
    sc_trace(mVcdFile, data_V_data_2_V_read, "(port)data_V_data_2_V_read");
    sc_trace(mVcdFile, res_V_data_0_V_din, "(port)res_V_data_0_V_din");
    sc_trace(mVcdFile, res_V_data_0_V_full_n, "(port)res_V_data_0_V_full_n");
    sc_trace(mVcdFile, res_V_data_0_V_write, "(port)res_V_data_0_V_write");
    sc_trace(mVcdFile, res_V_data_1_V_din, "(port)res_V_data_1_V_din");
    sc_trace(mVcdFile, res_V_data_1_V_full_n, "(port)res_V_data_1_V_full_n");
    sc_trace(mVcdFile, res_V_data_1_V_write, "(port)res_V_data_1_V_write");
    sc_trace(mVcdFile, res_V_data_2_V_din, "(port)res_V_data_2_V_din");
    sc_trace(mVcdFile, res_V_data_2_V_full_n, "(port)res_V_data_2_V_full_n");
    sc_trace(mVcdFile, res_V_data_2_V_write, "(port)res_V_data_2_V_write");
    sc_trace(mVcdFile, data_V_data_0_V_blk_n, "(port)data_V_data_0_V_blk_n");
    sc_trace(mVcdFile, data_V_data_1_V_blk_n, "(port)data_V_data_1_V_blk_n");
    sc_trace(mVcdFile, data_V_data_2_V_blk_n, "(port)data_V_data_2_V_blk_n");
    sc_trace(mVcdFile, res_V_data_0_V_blk_n, "(port)res_V_data_0_V_blk_n");
    sc_trace(mVcdFile, res_V_data_1_V_blk_n, "(port)res_V_data_1_V_blk_n");
    sc_trace(mVcdFile, res_V_data_2_V_blk_n, "(port)res_V_data_2_V_blk_n");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter5, "ap_enable_reg_pp0_iter5");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage2, "ap_CS_fsm_pp0_stage2");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage2_iter0, "ap_block_state3_pp0_stage2_iter0");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage2_iter1, "ap_block_state6_pp0_stage2_iter1");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage2_iter2, "ap_block_state9_pp0_stage2_iter2");
    sc_trace(mVcdFile, ap_block_state12_pp0_stage2_iter3, "ap_block_state12_pp0_stage2_iter3");
    sc_trace(mVcdFile, ap_block_state15_pp0_stage2_iter4, "ap_block_state15_pp0_stage2_iter4");
    sc_trace(mVcdFile, ap_block_pp0_stage2_11001, "ap_block_pp0_stage2_11001");
    sc_trace(mVcdFile, exp_table4_address0, "exp_table4_address0");
    sc_trace(mVcdFile, exp_table4_ce0, "exp_table4_ce0");
    sc_trace(mVcdFile, exp_table4_q0, "exp_table4_q0");
    sc_trace(mVcdFile, invert_table5_address0, "invert_table5_address0");
    sc_trace(mVcdFile, invert_table5_ce0, "invert_table5_ce0");
    sc_trace(mVcdFile, invert_table5_q0, "invert_table5_q0");
    sc_trace(mVcdFile, tmp_data_0_V_1_reg_627, "tmp_data_0_V_1_reg_627");
    sc_trace(mVcdFile, io_acc_block_signal_op17, "io_acc_block_signal_op17");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter1, "ap_block_state4_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter2, "ap_block_state7_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state10_pp0_stage0_iter3, "ap_block_state10_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state13_pp0_stage0_iter4, "ap_block_state13_pp0_stage0_iter4");
    sc_trace(mVcdFile, io_acc_block_signal_op131, "io_acc_block_signal_op131");
    sc_trace(mVcdFile, ap_block_state16_pp0_stage0_iter5, "ap_block_state16_pp0_stage0_iter5");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, tmp_data_1_V_1_reg_634, "tmp_data_1_V_1_reg_634");
    sc_trace(mVcdFile, tmp_data_2_V_1_reg_641, "tmp_data_2_V_1_reg_641");
    sc_trace(mVcdFile, icmp_ln1496_fu_192_p2, "icmp_ln1496_fu_192_p2");
    sc_trace(mVcdFile, icmp_ln1496_reg_648, "icmp_ln1496_reg_648");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage1, "ap_CS_fsm_pp0_stage1");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage1_iter0, "ap_block_state2_pp0_stage1_iter0");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage1_iter1, "ap_block_state5_pp0_stage1_iter1");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage1_iter2, "ap_block_state8_pp0_stage1_iter2");
    sc_trace(mVcdFile, ap_block_state11_pp0_stage1_iter3, "ap_block_state11_pp0_stage1_iter3");
    sc_trace(mVcdFile, ap_block_state14_pp0_stage1_iter4, "ap_block_state14_pp0_stage1_iter4");
    sc_trace(mVcdFile, ap_block_pp0_stage1_11001, "ap_block_pp0_stage1_11001");
    sc_trace(mVcdFile, x_max_V_fu_206_p3, "x_max_V_fu_206_p3");
    sc_trace(mVcdFile, x_max_V_reg_653, "x_max_V_reg_653");
    sc_trace(mVcdFile, y_V_fu_407_p3, "y_V_fu_407_p3");
    sc_trace(mVcdFile, y_V_reg_658, "y_V_reg_658");
    sc_trace(mVcdFile, y_V_1_fu_441_p3, "y_V_1_fu_441_p3");
    sc_trace(mVcdFile, y_V_1_reg_663, "y_V_1_reg_663");
    sc_trace(mVcdFile, y_V_2_fu_475_p3, "y_V_2_fu_475_p3");
    sc_trace(mVcdFile, y_V_2_reg_668, "y_V_2_reg_668");
    sc_trace(mVcdFile, exp_res_0_V_reg_678, "exp_res_0_V_reg_678");
    sc_trace(mVcdFile, exp_res_0_V_reg_678_pp0_iter2_reg, "exp_res_0_V_reg_678_pp0_iter2_reg");
    sc_trace(mVcdFile, exp_res_1_V_reg_689, "exp_res_1_V_reg_689");
    sc_trace(mVcdFile, exp_res_1_V_reg_689_pp0_iter3_reg, "exp_res_1_V_reg_689_pp0_iter3_reg");
    sc_trace(mVcdFile, exp_res_2_V_reg_700, "exp_res_2_V_reg_700");
    sc_trace(mVcdFile, exp_res_2_V_reg_700_pp0_iter3_reg, "exp_res_2_V_reg_700_pp0_iter3_reg");
    sc_trace(mVcdFile, ret_V_fu_501_p2, "ret_V_fu_501_p2");
    sc_trace(mVcdFile, ret_V_reg_707, "ret_V_reg_707");
    sc_trace(mVcdFile, y_V_3_fu_599_p3, "y_V_3_fu_599_p3");
    sc_trace(mVcdFile, y_V_3_reg_713, "y_V_3_reg_713");
    sc_trace(mVcdFile, inv_exp_sum_V_reg_723, "inv_exp_sum_V_reg_723");
    sc_trace(mVcdFile, sext_ln241_fu_611_p1, "sext_ln241_fu_611_p1");
    sc_trace(mVcdFile, sext_ln241_reg_728, "sext_ln241_reg_728");
    sc_trace(mVcdFile, zext_ln1118_fu_615_p1, "zext_ln1118_fu_615_p1");
    sc_trace(mVcdFile, tmp_data_0_V_reg_738, "tmp_data_0_V_reg_738");
    sc_trace(mVcdFile, zext_ln1118_1_fu_619_p1, "zext_ln1118_1_fu_619_p1");
    sc_trace(mVcdFile, tmp_data_1_V_reg_748, "tmp_data_1_V_reg_748");
    sc_trace(mVcdFile, zext_ln1118_2_fu_623_p1, "zext_ln1118_2_fu_623_p1");
    sc_trace(mVcdFile, tmp_data_2_V_reg_758, "tmp_data_2_V_reg_758");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0_reg, "ap_enable_reg_pp0_iter0_reg");
    sc_trace(mVcdFile, ap_block_pp0_stage2_subdone, "ap_block_pp0_stage2_subdone");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, zext_ln225_fu_483_p1, "zext_ln225_fu_483_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage1, "ap_block_pp0_stage1");
    sc_trace(mVcdFile, zext_ln225_1_fu_487_p1, "zext_ln225_1_fu_487_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage2, "ap_block_pp0_stage2");
    sc_trace(mVcdFile, zext_ln225_2_fu_491_p1, "zext_ln225_2_fu_491_p1");
    sc_trace(mVcdFile, zext_ln235_fu_607_p1, "zext_ln235_fu_607_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, grp_fu_153_p0, "grp_fu_153_p0");
    sc_trace(mVcdFile, grp_fu_153_p1, "grp_fu_153_p1");
    sc_trace(mVcdFile, grp_fu_153_p2, "grp_fu_153_p2");
    sc_trace(mVcdFile, select_ln65_fu_196_p3, "select_ln65_fu_196_p3");
    sc_trace(mVcdFile, icmp_ln1496_1_fu_201_p2, "icmp_ln1496_1_fu_201_p2");
    sc_trace(mVcdFile, sext_ln703_fu_213_p1, "sext_ln703_fu_213_p1");
    sc_trace(mVcdFile, sext_ln703_1_fu_216_p1, "sext_ln703_1_fu_216_p1");
    sc_trace(mVcdFile, sub_ln1193_fu_219_p2, "sub_ln1193_fu_219_p2");
    sc_trace(mVcdFile, tmp_7_fu_233_p3, "tmp_7_fu_233_p3");
    sc_trace(mVcdFile, tmp_5_fu_225_p3, "tmp_5_fu_225_p3");
    sc_trace(mVcdFile, xor_ln786_fu_241_p2, "xor_ln786_fu_241_p2");
    sc_trace(mVcdFile, xor_ln340_fu_259_p2, "xor_ln340_fu_259_p2");
    sc_trace(mVcdFile, sext_ln703_2_fu_271_p1, "sext_ln703_2_fu_271_p1");
    sc_trace(mVcdFile, sub_ln1193_1_fu_274_p2, "sub_ln1193_1_fu_274_p2");
    sc_trace(mVcdFile, tmp_10_fu_288_p3, "tmp_10_fu_288_p3");
    sc_trace(mVcdFile, tmp_9_fu_280_p3, "tmp_9_fu_280_p3");
    sc_trace(mVcdFile, xor_ln786_1_fu_296_p2, "xor_ln786_1_fu_296_p2");
    sc_trace(mVcdFile, xor_ln340_1_fu_314_p2, "xor_ln340_1_fu_314_p2");
    sc_trace(mVcdFile, sext_ln703_3_fu_326_p1, "sext_ln703_3_fu_326_p1");
    sc_trace(mVcdFile, sub_ln1193_2_fu_329_p2, "sub_ln1193_2_fu_329_p2");
    sc_trace(mVcdFile, tmp_12_fu_343_p3, "tmp_12_fu_343_p3");
    sc_trace(mVcdFile, tmp_11_fu_335_p3, "tmp_11_fu_335_p3");
    sc_trace(mVcdFile, xor_ln786_2_fu_351_p2, "xor_ln786_2_fu_351_p2");
    sc_trace(mVcdFile, xor_ln340_2_fu_369_p2, "xor_ln340_2_fu_369_p2");
    sc_trace(mVcdFile, xor_ln340_3_fu_253_p2, "xor_ln340_3_fu_253_p2");
    sc_trace(mVcdFile, tmp_fu_381_p4, "tmp_fu_381_p4");
    sc_trace(mVcdFile, and_ln786_fu_247_p2, "and_ln786_fu_247_p2");
    sc_trace(mVcdFile, or_ln340_fu_265_p2, "or_ln340_fu_265_p2");
    sc_trace(mVcdFile, select_ln340_fu_391_p3, "select_ln340_fu_391_p3");
    sc_trace(mVcdFile, select_ln388_fu_399_p3, "select_ln388_fu_399_p3");
    sc_trace(mVcdFile, xor_ln340_4_fu_308_p2, "xor_ln340_4_fu_308_p2");
    sc_trace(mVcdFile, tmp_6_fu_415_p4, "tmp_6_fu_415_p4");
    sc_trace(mVcdFile, and_ln786_1_fu_302_p2, "and_ln786_1_fu_302_p2");
    sc_trace(mVcdFile, or_ln340_1_fu_320_p2, "or_ln340_1_fu_320_p2");
    sc_trace(mVcdFile, select_ln340_2_fu_425_p3, "select_ln340_2_fu_425_p3");
    sc_trace(mVcdFile, select_ln388_1_fu_433_p3, "select_ln388_1_fu_433_p3");
    sc_trace(mVcdFile, xor_ln340_5_fu_363_p2, "xor_ln340_5_fu_363_p2");
    sc_trace(mVcdFile, tmp_8_fu_449_p4, "tmp_8_fu_449_p4");
    sc_trace(mVcdFile, and_ln786_2_fu_357_p2, "and_ln786_2_fu_357_p2");
    sc_trace(mVcdFile, or_ln340_2_fu_375_p2, "or_ln340_2_fu_375_p2");
    sc_trace(mVcdFile, select_ln340_4_fu_459_p3, "select_ln340_4_fu_459_p3");
    sc_trace(mVcdFile, select_ln388_2_fu_467_p3, "select_ln388_2_fu_467_p3");
    sc_trace(mVcdFile, zext_ln36_2_fu_498_p1, "zext_ln36_2_fu_498_p1");
    sc_trace(mVcdFile, zext_ln36_1_fu_495_p1, "zext_ln36_1_fu_495_p1");
    sc_trace(mVcdFile, rhs_V_fu_513_p1, "rhs_V_fu_513_p1");
    sc_trace(mVcdFile, lhs_V_fu_510_p1, "lhs_V_fu_510_p1");
    sc_trace(mVcdFile, ret_V_1_fu_516_p2, "ret_V_1_fu_516_p2");
    sc_trace(mVcdFile, zext_ln36_fu_507_p1, "zext_ln36_fu_507_p1");
    sc_trace(mVcdFile, p_Val2_9_fu_530_p2, "p_Val2_9_fu_530_p2");
    sc_trace(mVcdFile, p_Result_7_fu_535_p3, "p_Result_7_fu_535_p3");
    sc_trace(mVcdFile, p_Result_s_fu_522_p3, "p_Result_s_fu_522_p3");
    sc_trace(mVcdFile, xor_ln786_3_fu_543_p2, "xor_ln786_3_fu_543_p2");
    sc_trace(mVcdFile, xor_ln340_7_fu_561_p2, "xor_ln340_7_fu_561_p2");
    sc_trace(mVcdFile, xor_ln340_6_fu_555_p2, "xor_ln340_6_fu_555_p2");
    sc_trace(mVcdFile, tmp_s_fu_573_p4, "tmp_s_fu_573_p4");
    sc_trace(mVcdFile, underflow_fu_549_p2, "underflow_fu_549_p2");
    sc_trace(mVcdFile, or_ln340_3_fu_567_p2, "or_ln340_3_fu_567_p2");
    sc_trace(mVcdFile, select_ln340_6_fu_583_p3, "select_ln340_6_fu_583_p3");
    sc_trace(mVcdFile, select_ln388_3_fu_591_p3, "select_ln388_3_fu_591_p3");
    sc_trace(mVcdFile, grp_fu_153_ce, "grp_fu_153_ce");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0_0to4, "ap_idle_pp0_0to4");
    sc_trace(mVcdFile, ap_reset_idle_pp0, "ap_reset_idle_pp0");
    sc_trace(mVcdFile, ap_idle_pp0_1to5, "ap_idle_pp0_1to5");
    sc_trace(mVcdFile, ap_block_pp0_stage1_subdone, "ap_block_pp0_stage1_subdone");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::~softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete exp_table4_U;
    delete invert_table5_U;
    delete myproject_axi_mul_17ns_18s_28_2_1_U434;
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_pp0_stage0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read())) {
            ap_enable_reg_pp0_iter0_reg = ap_start.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage2_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage2_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage2_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage2_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter5 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage2_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter5 = ap_enable_reg_pp0_iter4.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
                    esl_seteq<1,1,1>(ap_enable_reg_pp0_iter4.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter5 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        exp_res_0_V_reg_678 = exp_table4_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0))) {
        exp_res_0_V_reg_678_pp0_iter2_reg = exp_res_0_V_reg_678.read();
        sext_ln241_reg_728 = sext_ln241_fu_611_p1.read();
        x_max_V_reg_653 = x_max_V_fu_206_p3.read();
        y_V_3_reg_713 = y_V_3_fu_599_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        exp_res_1_V_reg_689 = exp_table4_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exp_res_1_V_reg_689_pp0_iter3_reg = exp_res_1_V_reg_689.read();
        tmp_data_0_V_1_reg_627 = data_V_data_0_V_dout.read();
        tmp_data_1_V_1_reg_634 = data_V_data_1_V_dout.read();
        tmp_data_2_V_1_reg_641 = data_V_data_2_V_dout.read();
        y_V_1_reg_663 = y_V_1_fu_441_p3.read();
        y_V_2_reg_668 = y_V_2_fu_475_p3.read();
        y_V_reg_658 = y_V_fu_407_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        exp_res_2_V_reg_700 = exp_table4_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0))) {
        exp_res_2_V_reg_700_pp0_iter3_reg = exp_res_2_V_reg_700.read();
        icmp_ln1496_reg_648 = icmp_ln1496_fu_192_p2.read();
        inv_exp_sum_V_reg_723 = invert_table5_q0.read();
        ret_V_reg_707 = ret_V_fu_501_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()))) {
        tmp_data_0_V_reg_738 = grp_fu_153_p2.read().range(27, 8);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()))) {
        tmp_data_1_V_reg_748 = grp_fu_153_p2.read().range(27, 8);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()))) {
        tmp_data_2_V_reg_758 = grp_fu_153_p2.read().range(27, 8);
    }
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_and_ln786_1_fu_302_p2() {
    and_ln786_1_fu_302_p2 = (tmp_9_fu_280_p3.read() & xor_ln786_1_fu_296_p2.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_and_ln786_2_fu_357_p2() {
    and_ln786_2_fu_357_p2 = (tmp_11_fu_335_p3.read() & xor_ln786_2_fu_351_p2.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_and_ln786_fu_247_p2() {
    and_ln786_fu_247_p2 = (tmp_5_fu_225_p3.read() & xor_ln786_fu_241_p2.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[0];
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_CS_fsm_pp0_stage1() {
    ap_CS_fsm_pp0_stage1 = ap_CS_fsm.read()[1];
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_CS_fsm_pp0_stage2() {
    ap_CS_fsm_pp0_stage2 = ap_CS_fsm.read()[2];
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op17.read()))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op131.read())));
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op17.read()))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op131.read())));
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op17.read()))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op131.read())));
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_block_pp0_stage1() {
    ap_block_pp0_stage1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_block_pp0_stage1_11001() {
    ap_block_pp0_stage1_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_block_pp0_stage1_subdone() {
    ap_block_pp0_stage1_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_block_pp0_stage2() {
    ap_block_pp0_stage2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_block_pp0_stage2_11001() {
    ap_block_pp0_stage2_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_block_pp0_stage2_subdone() {
    ap_block_pp0_stage2_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_block_state10_pp0_stage0_iter3() {
    ap_block_state10_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_block_state11_pp0_stage1_iter3() {
    ap_block_state11_pp0_stage1_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_block_state12_pp0_stage2_iter3() {
    ap_block_state12_pp0_stage2_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_block_state13_pp0_stage0_iter4() {
    ap_block_state13_pp0_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_block_state14_pp0_stage1_iter4() {
    ap_block_state14_pp0_stage1_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_block_state15_pp0_stage2_iter4() {
    ap_block_state15_pp0_stage2_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_block_state16_pp0_stage0_iter5() {
    ap_block_state16_pp0_stage0_iter5 = esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op131.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op17.read()));
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_block_state2_pp0_stage1_iter0() {
    ap_block_state2_pp0_stage1_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_block_state3_pp0_stage2_iter0() {
    ap_block_state3_pp0_stage2_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_block_state4_pp0_stage0_iter1() {
    ap_block_state4_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_block_state5_pp0_stage1_iter1() {
    ap_block_state5_pp0_stage1_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_block_state6_pp0_stage2_iter1() {
    ap_block_state6_pp0_stage2_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_block_state7_pp0_stage0_iter2() {
    ap_block_state7_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_block_state8_pp0_stage1_iter2() {
    ap_block_state8_pp0_stage1_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_block_state9_pp0_stage2_iter2() {
    ap_block_state9_pp0_stage2_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_enable_reg_pp0_iter0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read())) {
        ap_enable_reg_pp0_iter0 = ap_start.read();
    } else {
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg.read();
    }
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter5.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_idle_pp0_0to4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()))) {
        ap_idle_pp0_0to4 = ap_const_logic_1;
    } else {
        ap_idle_pp0_0to4 = ap_const_logic_0;
    }
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_idle_pp0_1to5() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter5.read()))) {
        ap_idle_pp0_1to5 = ap_const_logic_1;
    } else {
        ap_idle_pp0_1to5 = ap_const_logic_0;
    }
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_reset_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0_0to4.read()))) {
        ap_reset_idle_pp0 = ap_const_logic_1;
    } else {
        ap_reset_idle_pp0 = ap_const_logic_0;
    }
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_data_V_data_0_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        data_V_data_0_V_blk_n = data_V_data_0_V_empty_n.read();
    } else {
        data_V_data_0_V_blk_n = ap_const_logic_1;
    }
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_data_V_data_0_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_V_data_0_V_read = ap_const_logic_1;
    } else {
        data_V_data_0_V_read = ap_const_logic_0;
    }
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_data_V_data_1_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        data_V_data_1_V_blk_n = data_V_data_1_V_empty_n.read();
    } else {
        data_V_data_1_V_blk_n = ap_const_logic_1;
    }
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_data_V_data_1_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_V_data_1_V_read = ap_const_logic_1;
    } else {
        data_V_data_1_V_read = ap_const_logic_0;
    }
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_data_V_data_2_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        data_V_data_2_V_blk_n = data_V_data_2_V_empty_n.read();
    } else {
        data_V_data_2_V_blk_n = ap_const_logic_1;
    }
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_data_V_data_2_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_V_data_2_V_read = ap_const_logic_1;
    } else {
        data_V_data_2_V_read = ap_const_logic_0;
    }
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_exp_table4_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        exp_table4_address0 =  (sc_lv<10>) (zext_ln225_2_fu_491_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage2.read(), ap_const_boolean_0))) {
        exp_table4_address0 =  (sc_lv<10>) (zext_ln225_1_fu_487_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
        exp_table4_address0 =  (sc_lv<10>) (zext_ln225_fu_483_p1.read());
    } else {
        exp_table4_address0 = "XXXXXXXXXX";
    }
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_exp_table4_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read())))) {
        exp_table4_ce0 = ap_const_logic_1;
    } else {
        exp_table4_ce0 = ap_const_logic_0;
    }
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_grp_fu_153_ce() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0)))) {
        grp_fu_153_ce = ap_const_logic_1;
    } else {
        grp_fu_153_ce = ap_const_logic_0;
    }
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_grp_fu_153_p0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
        grp_fu_153_p0 =  (sc_lv<17>) (zext_ln1118_2_fu_623_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()))) {
        grp_fu_153_p0 =  (sc_lv<17>) (zext_ln1118_1_fu_619_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage2.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()))) {
        grp_fu_153_p0 =  (sc_lv<17>) (zext_ln1118_fu_615_p1.read());
    } else {
        grp_fu_153_p0 =  (sc_lv<17>) ("XXXXXXXXXXXXXXXXX");
    }
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_grp_fu_153_p1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0)))) {
        grp_fu_153_p1 =  (sc_lv<18>) (sext_ln241_reg_728.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage2.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()))) {
        grp_fu_153_p1 =  (sc_lv<18>) (sext_ln241_fu_611_p1.read());
    } else {
        grp_fu_153_p1 =  (sc_lv<18>) ("XXXXXXXXXXXXXXXXXX");
    }
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_icmp_ln1496_1_fu_201_p2() {
    icmp_ln1496_1_fu_201_p2 = (!select_ln65_fu_196_p3.read().is_01() || !tmp_data_2_V_1_reg_641.read().is_01())? sc_lv<1>(): (sc_bigint<20>(select_ln65_fu_196_p3.read()) < sc_bigint<20>(tmp_data_2_V_1_reg_641.read()));
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_icmp_ln1496_fu_192_p2() {
    icmp_ln1496_fu_192_p2 = (!tmp_data_0_V_1_reg_627.read().is_01() || !tmp_data_1_V_1_reg_634.read().is_01())? sc_lv<1>(): (sc_bigint<20>(tmp_data_0_V_1_reg_627.read()) < sc_bigint<20>(tmp_data_1_V_1_reg_634.read()));
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_invert_table5_address0() {
    invert_table5_address0 =  (sc_lv<10>) (zext_ln235_fu_607_p1.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_invert_table5_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()))) {
        invert_table5_ce0 = ap_const_logic_1;
    } else {
        invert_table5_ce0 = ap_const_logic_0;
    }
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_io_acc_block_signal_op131() {
    io_acc_block_signal_op131 = (res_V_data_0_V_full_n.read() & res_V_data_1_V_full_n.read() & res_V_data_2_V_full_n.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_io_acc_block_signal_op17() {
    io_acc_block_signal_op17 = (data_V_data_0_V_empty_n.read() & data_V_data_1_V_empty_n.read() & data_V_data_2_V_empty_n.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_lhs_V_fu_510_p1() {
    lhs_V_fu_510_p1 = esl_sext<19,18>(ret_V_reg_707.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_or_ln340_1_fu_320_p2() {
    or_ln340_1_fu_320_p2 = (tmp_10_fu_288_p3.read() | xor_ln340_1_fu_314_p2.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_or_ln340_2_fu_375_p2() {
    or_ln340_2_fu_375_p2 = (tmp_12_fu_343_p3.read() | xor_ln340_2_fu_369_p2.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_or_ln340_3_fu_567_p2() {
    or_ln340_3_fu_567_p2 = (p_Result_7_fu_535_p3.read() | xor_ln340_7_fu_561_p2.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_or_ln340_fu_265_p2() {
    or_ln340_fu_265_p2 = (tmp_7_fu_233_p3.read() | xor_ln340_fu_259_p2.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_p_Result_7_fu_535_p3() {
    p_Result_7_fu_535_p3 = p_Val2_9_fu_530_p2.read().range(17, 17);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_p_Result_s_fu_522_p3() {
    p_Result_s_fu_522_p3 = ret_V_1_fu_516_p2.read().range(18, 18);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_p_Val2_9_fu_530_p2() {
    p_Val2_9_fu_530_p2 = (!zext_ln36_fu_507_p1.read().is_01() || !ret_V_reg_707.read().is_01())? sc_lv<18>(): (sc_biguint<18>(zext_ln36_fu_507_p1.read()) + sc_bigint<18>(ret_V_reg_707.read()));
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_res_V_data_0_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()))) {
        res_V_data_0_V_blk_n = res_V_data_0_V_full_n.read();
    } else {
        res_V_data_0_V_blk_n = ap_const_logic_1;
    }
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_res_V_data_0_V_din() {
    res_V_data_0_V_din = tmp_data_0_V_reg_738.read();
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_res_V_data_0_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        res_V_data_0_V_write = ap_const_logic_1;
    } else {
        res_V_data_0_V_write = ap_const_logic_0;
    }
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_res_V_data_1_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()))) {
        res_V_data_1_V_blk_n = res_V_data_1_V_full_n.read();
    } else {
        res_V_data_1_V_blk_n = ap_const_logic_1;
    }
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_res_V_data_1_V_din() {
    res_V_data_1_V_din = tmp_data_1_V_reg_748.read();
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_res_V_data_1_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        res_V_data_1_V_write = ap_const_logic_1;
    } else {
        res_V_data_1_V_write = ap_const_logic_0;
    }
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_res_V_data_2_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()))) {
        res_V_data_2_V_blk_n = res_V_data_2_V_full_n.read();
    } else {
        res_V_data_2_V_blk_n = ap_const_logic_1;
    }
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_res_V_data_2_V_din() {
    res_V_data_2_V_din = tmp_data_2_V_reg_758.read();
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_res_V_data_2_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        res_V_data_2_V_write = ap_const_logic_1;
    } else {
        res_V_data_2_V_write = ap_const_logic_0;
    }
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ret_V_1_fu_516_p2() {
    ret_V_1_fu_516_p2 = (!rhs_V_fu_513_p1.read().is_01() || !lhs_V_fu_510_p1.read().is_01())? sc_lv<19>(): (sc_biguint<19>(rhs_V_fu_513_p1.read()) + sc_bigint<19>(lhs_V_fu_510_p1.read()));
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ret_V_fu_501_p2() {
    ret_V_fu_501_p2 = (!zext_ln36_2_fu_498_p1.read().is_01() || !zext_ln36_1_fu_495_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(zext_ln36_2_fu_498_p1.read()) + sc_biguint<18>(zext_ln36_1_fu_495_p1.read()));
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_rhs_V_fu_513_p1() {
    rhs_V_fu_513_p1 = esl_zext<19,17>(exp_res_2_V_reg_700.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_select_ln340_2_fu_425_p3() {
    select_ln340_2_fu_425_p3 = (!xor_ln340_4_fu_308_p2.read()[0].is_01())? sc_lv<10>(): ((xor_ln340_4_fu_308_p2.read()[0].to_bool())? ap_const_lv10_1FF: tmp_6_fu_415_p4.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_select_ln340_4_fu_459_p3() {
    select_ln340_4_fu_459_p3 = (!xor_ln340_5_fu_363_p2.read()[0].is_01())? sc_lv<10>(): ((xor_ln340_5_fu_363_p2.read()[0].to_bool())? ap_const_lv10_1FF: tmp_8_fu_449_p4.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_select_ln340_6_fu_583_p3() {
    select_ln340_6_fu_583_p3 = (!xor_ln340_6_fu_555_p2.read()[0].is_01())? sc_lv<10>(): ((xor_ln340_6_fu_555_p2.read()[0].to_bool())? ap_const_lv10_1FF: tmp_s_fu_573_p4.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_select_ln340_fu_391_p3() {
    select_ln340_fu_391_p3 = (!xor_ln340_3_fu_253_p2.read()[0].is_01())? sc_lv<10>(): ((xor_ln340_3_fu_253_p2.read()[0].to_bool())? ap_const_lv10_1FF: tmp_fu_381_p4.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_select_ln388_1_fu_433_p3() {
    select_ln388_1_fu_433_p3 = (!and_ln786_1_fu_302_p2.read()[0].is_01())? sc_lv<10>(): ((and_ln786_1_fu_302_p2.read()[0].to_bool())? ap_const_lv10_200: tmp_6_fu_415_p4.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_select_ln388_2_fu_467_p3() {
    select_ln388_2_fu_467_p3 = (!and_ln786_2_fu_357_p2.read()[0].is_01())? sc_lv<10>(): ((and_ln786_2_fu_357_p2.read()[0].to_bool())? ap_const_lv10_200: tmp_8_fu_449_p4.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_select_ln388_3_fu_591_p3() {
    select_ln388_3_fu_591_p3 = (!underflow_fu_549_p2.read()[0].is_01())? sc_lv<10>(): ((underflow_fu_549_p2.read()[0].to_bool())? ap_const_lv10_200: tmp_s_fu_573_p4.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_select_ln388_fu_399_p3() {
    select_ln388_fu_399_p3 = (!and_ln786_fu_247_p2.read()[0].is_01())? sc_lv<10>(): ((and_ln786_fu_247_p2.read()[0].to_bool())? ap_const_lv10_200: tmp_fu_381_p4.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_select_ln65_fu_196_p3() {
    select_ln65_fu_196_p3 = (!icmp_ln1496_reg_648.read()[0].is_01())? sc_lv<20>(): ((icmp_ln1496_reg_648.read()[0].to_bool())? tmp_data_1_V_1_reg_634.read(): tmp_data_0_V_1_reg_627.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_sext_ln241_fu_611_p1() {
    sext_ln241_fu_611_p1 = esl_sext<28,18>(inv_exp_sum_V_reg_723.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_sext_ln703_1_fu_216_p1() {
    sext_ln703_1_fu_216_p1 = esl_sext<21,20>(x_max_V_reg_653.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_sext_ln703_2_fu_271_p1() {
    sext_ln703_2_fu_271_p1 = esl_sext<21,20>(tmp_data_1_V_1_reg_634.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_sext_ln703_3_fu_326_p1() {
    sext_ln703_3_fu_326_p1 = esl_sext<21,20>(tmp_data_2_V_1_reg_641.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_sext_ln703_fu_213_p1() {
    sext_ln703_fu_213_p1 = esl_sext<21,20>(tmp_data_0_V_1_reg_627.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_sub_ln1193_1_fu_274_p2() {
    sub_ln1193_1_fu_274_p2 = (!sext_ln703_2_fu_271_p1.read().is_01() || !sext_ln703_1_fu_216_p1.read().is_01())? sc_lv<21>(): (sc_bigint<21>(sext_ln703_2_fu_271_p1.read()) - sc_bigint<21>(sext_ln703_1_fu_216_p1.read()));
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_sub_ln1193_2_fu_329_p2() {
    sub_ln1193_2_fu_329_p2 = (!sext_ln703_3_fu_326_p1.read().is_01() || !sext_ln703_1_fu_216_p1.read().is_01())? sc_lv<21>(): (sc_bigint<21>(sext_ln703_3_fu_326_p1.read()) - sc_bigint<21>(sext_ln703_1_fu_216_p1.read()));
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_sub_ln1193_fu_219_p2() {
    sub_ln1193_fu_219_p2 = (!sext_ln703_fu_213_p1.read().is_01() || !sext_ln703_1_fu_216_p1.read().is_01())? sc_lv<21>(): (sc_bigint<21>(sext_ln703_fu_213_p1.read()) - sc_bigint<21>(sext_ln703_1_fu_216_p1.read()));
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_tmp_10_fu_288_p3() {
    tmp_10_fu_288_p3 = sub_ln1193_1_fu_274_p2.read().range(19, 19);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_tmp_11_fu_335_p3() {
    tmp_11_fu_335_p3 = sub_ln1193_2_fu_329_p2.read().range(20, 20);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_tmp_12_fu_343_p3() {
    tmp_12_fu_343_p3 = sub_ln1193_2_fu_329_p2.read().range(19, 19);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_tmp_5_fu_225_p3() {
    tmp_5_fu_225_p3 = sub_ln1193_fu_219_p2.read().range(20, 20);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_tmp_6_fu_415_p4() {
    tmp_6_fu_415_p4 = sub_ln1193_1_fu_274_p2.read().range(19, 10);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_tmp_7_fu_233_p3() {
    tmp_7_fu_233_p3 = sub_ln1193_fu_219_p2.read().range(19, 19);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_tmp_8_fu_449_p4() {
    tmp_8_fu_449_p4 = sub_ln1193_2_fu_329_p2.read().range(19, 10);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_tmp_9_fu_280_p3() {
    tmp_9_fu_280_p3 = sub_ln1193_1_fu_274_p2.read().range(20, 20);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_tmp_fu_381_p4() {
    tmp_fu_381_p4 = sub_ln1193_fu_219_p2.read().range(19, 10);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_tmp_s_fu_573_p4() {
    tmp_s_fu_573_p4 = p_Val2_9_fu_530_p2.read().range(17, 8);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_underflow_fu_549_p2() {
    underflow_fu_549_p2 = (p_Result_s_fu_522_p3.read() & xor_ln786_3_fu_543_p2.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_x_max_V_fu_206_p3() {
    x_max_V_fu_206_p3 = (!icmp_ln1496_1_fu_201_p2.read()[0].is_01())? sc_lv<20>(): ((icmp_ln1496_1_fu_201_p2.read()[0].to_bool())? tmp_data_2_V_1_reg_641.read(): select_ln65_fu_196_p3.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_xor_ln340_1_fu_314_p2() {
    xor_ln340_1_fu_314_p2 = (tmp_9_fu_280_p3.read() ^ ap_const_lv1_1);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_xor_ln340_2_fu_369_p2() {
    xor_ln340_2_fu_369_p2 = (tmp_11_fu_335_p3.read() ^ ap_const_lv1_1);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_xor_ln340_3_fu_253_p2() {
    xor_ln340_3_fu_253_p2 = (tmp_5_fu_225_p3.read() ^ tmp_7_fu_233_p3.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_xor_ln340_4_fu_308_p2() {
    xor_ln340_4_fu_308_p2 = (tmp_9_fu_280_p3.read() ^ tmp_10_fu_288_p3.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_xor_ln340_5_fu_363_p2() {
    xor_ln340_5_fu_363_p2 = (tmp_11_fu_335_p3.read() ^ tmp_12_fu_343_p3.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_xor_ln340_6_fu_555_p2() {
    xor_ln340_6_fu_555_p2 = (p_Result_s_fu_522_p3.read() ^ p_Result_7_fu_535_p3.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_xor_ln340_7_fu_561_p2() {
    xor_ln340_7_fu_561_p2 = (p_Result_s_fu_522_p3.read() ^ ap_const_lv1_1);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_xor_ln340_fu_259_p2() {
    xor_ln340_fu_259_p2 = (tmp_5_fu_225_p3.read() ^ ap_const_lv1_1);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_xor_ln786_1_fu_296_p2() {
    xor_ln786_1_fu_296_p2 = (tmp_10_fu_288_p3.read() ^ ap_const_lv1_1);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_xor_ln786_2_fu_351_p2() {
    xor_ln786_2_fu_351_p2 = (tmp_12_fu_343_p3.read() ^ ap_const_lv1_1);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_xor_ln786_3_fu_543_p2() {
    xor_ln786_3_fu_543_p2 = (p_Result_7_fu_535_p3.read() ^ ap_const_lv1_1);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_xor_ln786_fu_241_p2() {
    xor_ln786_fu_241_p2 = (tmp_7_fu_233_p3.read() ^ ap_const_lv1_1);
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_y_V_1_fu_441_p3() {
    y_V_1_fu_441_p3 = (!or_ln340_1_fu_320_p2.read()[0].is_01())? sc_lv<10>(): ((or_ln340_1_fu_320_p2.read()[0].to_bool())? select_ln340_2_fu_425_p3.read(): select_ln388_1_fu_433_p3.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_y_V_2_fu_475_p3() {
    y_V_2_fu_475_p3 = (!or_ln340_2_fu_375_p2.read()[0].is_01())? sc_lv<10>(): ((or_ln340_2_fu_375_p2.read()[0].to_bool())? select_ln340_4_fu_459_p3.read(): select_ln388_2_fu_467_p3.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_y_V_3_fu_599_p3() {
    y_V_3_fu_599_p3 = (!or_ln340_3_fu_567_p2.read()[0].is_01())? sc_lv<10>(): ((or_ln340_3_fu_567_p2.read()[0].to_bool())? select_ln340_6_fu_583_p3.read(): select_ln388_3_fu_591_p3.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_y_V_fu_407_p3() {
    y_V_fu_407_p3 = (!or_ln340_fu_265_p2.read()[0].is_01())? sc_lv<10>(): ((or_ln340_fu_265_p2.read()[0].to_bool())? select_ln340_fu_391_p3.read(): select_ln388_fu_399_p3.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_zext_ln1118_1_fu_619_p1() {
    zext_ln1118_1_fu_619_p1 = esl_zext<28,17>(exp_res_1_V_reg_689_pp0_iter3_reg.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_zext_ln1118_2_fu_623_p1() {
    zext_ln1118_2_fu_623_p1 = esl_zext<28,17>(exp_res_2_V_reg_700_pp0_iter3_reg.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_zext_ln1118_fu_615_p1() {
    zext_ln1118_fu_615_p1 = esl_zext<28,17>(exp_res_0_V_reg_678_pp0_iter2_reg.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_zext_ln225_1_fu_487_p1() {
    zext_ln225_1_fu_487_p1 = esl_zext<64,10>(y_V_1_reg_663.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_zext_ln225_2_fu_491_p1() {
    zext_ln225_2_fu_491_p1 = esl_zext<64,10>(y_V_2_reg_668.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_zext_ln225_fu_483_p1() {
    zext_ln225_fu_483_p1 = esl_zext<64,10>(y_V_reg_658.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_zext_ln235_fu_607_p1() {
    zext_ln235_fu_607_p1 = esl_zext<64,10>(y_V_3_reg_713.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_zext_ln36_1_fu_495_p1() {
    zext_ln36_1_fu_495_p1 = esl_zext<18,17>(exp_res_1_V_reg_689.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_zext_ln36_2_fu_498_p1() {
    zext_ln36_2_fu_498_p1 = esl_zext<18,17>(exp_res_0_V_reg_678.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_zext_ln36_fu_507_p1() {
    zext_ln36_fu_507_p1 = esl_zext<18,17>(exp_res_2_V_reg_700.read());
}

void softmax_stable_array_array_ap_fixed_20_8_5_3_0_3u_softmax_config28_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_reset_idle_pp0.read(), ap_const_logic_0) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0_1to5.read())))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            } else if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reset_idle_pp0.read()))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 2 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            }
            break;
        case 4 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage2_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<3>) ("XXX");
            break;
    }
}

}

